import { countriesType } from "../interfaces";
//English content
const english = {
  edit: "Edit",
  myJobs: "My Jobs",
    createJob: "Create Job",
    proposals: "Proposals",
    create: "Create",
  donhave:"You don't have an account",
  createOne:"Create one",
  alreadySignedInMessage:"You are already signed in.",
  organizationName: "Organization Name",
  notMemeber:"Not member?",
  password:"Password",
  signUp:"Sign up",
  fname:"First Name",
  lname:"Last name",
  email:"Email",
  role:"Role",
  employee:"Employee",
  employer:"Employer",
  haveAccount:"Already have an account",
  logIn:"Log in",
  home_link: "Home",
  sent_link: "Applied",
  saved_link: "Bookmark",
  explore_link: "Discover",
  dashboard_link: "Dashboard",
  find_job: "Find Jobs",
  hero_header: "Step Into Your Future with the Perfect Job",
  hero_paragraph:
    "Browse thousands of openings, apply in seconds, and land the role you deserve.",
  job_posted: "Jobs Posted",
  active_users: "Active Job Seekers",
  campany_amount: "Companies Hiring",
  motive_header: "The best way to get Job",
  motive_paragraph:
    "Turn every job application into a real opportunity with expert guidance on networking, personal branding, and interview mastery.",
  about_us: "About Us",
  about_paragraph:
    "Jobify is a neutral, autonomous organization that connects employers with job seekers worldwide. Founded in 2026 by Bereket Girma, Jobify operates in 80+ countries, simplifying hiring and job searching through a trusted and user-friendly platform.",
  staf_header: "Our Community",
  footer_paragraph:
    "Jobify connects job seekers with the best opportunities worldwide. Apply in seconds and land your dream role.",
  links:"Quick Link",
  categories:"Catagories",
  location:"Location",
  jobType:"Job Type",
  salary:"Income",
  jobSearchPlaceholder:"Search for job",
  proposalPlaceholder:"Enter proposal details...",
 writeProposal:"Write Proposal",
  markdownSupport:"Mark formating supported",
  headline:"Land Your Job",
  careers:"Careers",
  below:"Below",
  send:"Send",
  dashboard:"Dashboard",
  workspace:"Workspace",
  inbox:"Inbox",
  name:"Name",
  post:"Post",
  team:"Our Team",
  aboutJob:"About the job",
  signOut:"Sign out",
  jobDetails:"Write Job Detail",
  title:"Title",
  language:"Language",
  apply:"Apply",
  learn_more:"Learn more",
  phone:"Phone",
  right:"All rights reserved.",
  footer_about_paragraph:"Founded in 2026 by Bereket Girma, Jobify operates in 80+ countries, simplifying hiring and job searching.",
  about:"About",
  contact:"Contact"
};
const teamsEn = [
  {
    name: "Oliver Benjamin",
    img: "/photo-1560250097-0b93528c311a.avif",
    description:
      "Leading strategy and vision to scale hiring platforms AI",
    stars: 4.5,
    halfStar: true,
    color: "bg-sky-600",
    title: "CEO",
  },
  {
    name: "Emily Grace",
    img: "/photo-1494790108377-be9c29b29330.avif",
    description:
      "Managing teams and delivery to ensure reliable operations",
    stars: 5,
    halfStar: false,
    color: "bg-pink-500",
    title: "Team Lead",
  },
  {
    name: "Alexander Carter",
    img: "/photo-1599566150163-29194dcaad36.avif",
    description:
      "Overseeing finance planning compliance and long term rise",
    stars: 5,
    halfStar: false,
    color: "bg-green-500",
    title: "CFO",
  },
  {
    name: "Thomas Anderson",
    img: "/premium_photo-1689539137236-b68e436248de.avif",
    description:
      "Supporting daily tasks coordination and smooth core flow!",
    stars: 3,
    halfStar: true,
    color: "bg-yellow-500",
    title: "Assistant",
  },
];
const categoriesEn = [
    { id: 1, name: "Healthcare & Medical" },
    { id: 2, name: "Information Technology (IT) & Software" },
    { id: 3, name: "Education & Teaching" },
    { id: 4, name: "Engineering & Technical" },
    { id: 5, name: "Finance & Accounting" },
    { id: 6, name: "Sales & Marketing" },
    { id: 7, name: "Human Resources & Administration" },
    { id: 8, name: "Creative & Design" },
    { id: 9, name: "Hospitality & Tourism" },
    { id: 10, name: "Manufacturing & Trades" },
  ];
const jobTypesEn = [
    { id: 1, name: "Full-time" },
    { id: 2, name: "Part-time" },
    { id: 3, name: "Contract" },
    { id: 4, name: "Temporary" },
    { id: 5, name: "Internship" },
    { id: 6, name: "Freelance" },
    { id: 7, name: "Remote" },
    { id: 8, name: "Hybrid" },
    { id: 9, name: "On-site" },
    { id: 10, name: "Seasonal" },
    { id: 11, name: "Volunteer" },
    { id: 12, name: "Apprenticeship" },
  ];
const countriesEn:countriesType[]  = [
  { id: 1, name: "Afghanistan", flag: "https://flagcdn.com/w40/af.png" },
  { id: 2, name: "Åland Islands", flag: "https://flagcdn.com/w40/ax.png" },
  { id: 3, name: "Albania", flag: "https://flagcdn.com/w40/al.png" },
  { id: 4, name: "Algeria", flag: "https://flagcdn.com/w40/dz.png" },
  { id: 5, name: "American Samoa", flag: "https://flagcdn.com/w40/as.png" },
  { id: 6, name: "Andorra", flag: "https://flagcdn.com/w40/ad.png" },
  { id: 7, name: "Angola", flag: "https://flagcdn.com/w40/ao.png" },
  { id: 8, name: "Anguilla", flag: "https://flagcdn.com/w40/ai.png" },
  { id: 9, name: "Antarctica", flag: "https://flagcdn.com/w40/aq.png" },
  { id: 10, name: "Antigua and Barbuda", flag: "https://flagcdn.com/w40/ag.png" },

  { id: 11, name: "Argentina", flag: "https://flagcdn.com/w40/ar.png" },
  { id: 12, name: "Armenia", flag: "https://flagcdn.com/w40/am.png" },
  { id: 13, name: "Aruba", flag: "https://flagcdn.com/w40/aw.png" },
  { id: 14, name: "Australia", flag: "https://flagcdn.com/w40/au.png" },
  { id: 15, name: "Austria", flag: "https://flagcdn.com/w40/at.png" },
  { id: 16, name: "Azerbaijan", flag: "https://flagcdn.com/w40/az.png" },
  { id: 17, name: "Bahamas", flag: "https://flagcdn.com/w40/bs.png" },
  { id: 18, name: "Bahrain", flag: "https://flagcdn.com/w40/bh.png" },
  { id: 19, name: "Bangladesh", flag: "https://flagcdn.com/w40/bd.png" },
  { id: 20, name: "Barbados", flag: "https://flagcdn.com/w40/bb.png" },

  { id: 21, name: "Belarus", flag: "https://flagcdn.com/w40/by.png" },
  { id: 22, name: "Belgium", flag: "https://flagcdn.com/w40/be.png" },
  { id: 23, name: "Belize", flag: "https://flagcdn.com/w40/bz.png" },
  { id: 24, name: "Benin", flag: "https://flagcdn.com/w40/bj.png" },
  { id: 25, name: "Bermuda", flag: "https://flagcdn.com/w40/bm.png" },
  { id: 26, name: "Bhutan", flag: "https://flagcdn.com/w40/bt.png" },
  { id: 27, name: "Bolivia", flag: "https://flagcdn.com/w40/bo.png" },
  { id: 28, name: "Bonaire, Sint Eustatius and Saba", flag: "https://flagcdn.com/w40/bq.png" },
  { id: 29, name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/w40/ba.png" },
  { id: 30, name: "Botswana", flag: "https://flagcdn.com/w40/bw.png" },

  { id: 31, name: "Bouvet Island", flag: "https://flagcdn.com/w40/bv.png" },
  { id: 32, name: "Brazil", flag: "https://flagcdn.com/w40/br.png" },
  { id: 33, name: "British Indian Ocean Territory", flag: "https://flagcdn.com/w40/io.png" },
  { id: 34, name: "Brunei", flag: "https://flagcdn.com/w40/bn.png" },
  { id: 35, name: "Bulgaria", flag: "https://flagcdn.com/w40/bg.png" },
  { id: 36, name: "Burkina Faso", flag: "https://flagcdn.com/w40/bf.png" },
  { id: 37, name: "Burundi", flag: "https://flagcdn.com/w40/bi.png" },
  { id: 38, name: "Cabo Verde", flag: "https://flagcdn.com/w40/cv.png" },
  { id: 39, name: "Cambodia", flag: "https://flagcdn.com/w40/kh.png" },
  { id: 40, name: "Cameroon", flag: "https://flagcdn.com/w40/cm.png" },

  { id: 41, name: "Canada", flag: "https://flagcdn.com/w40/ca.png" },
  { id: 42, name: "Cayman Islands", flag: "https://flagcdn.com/w40/ky.png" },
  { id: 43, name: "Central African Republic", flag: "https://flagcdn.com/w40/cf.png" },
  { id: 44, name: "Chad", flag: "https://flagcdn.com/w40/td.png" },
  { id: 45, name: "Chile", flag: "https://flagcdn.com/w40/cl.png" },
  { id: 46, name: "China", flag: "https://flagcdn.com/w40/cn.png" },
  { id: 47, name: "Christmas Island", flag: "https://flagcdn.com/w40/cx.png" },
  { id: 48, name: "Cocos (Keeling) Islands", flag: "https://flagcdn.com/w40/cc.png" },
  { id: 49, name: "Colombia", flag: "https://flagcdn.com/w40/co.png" },
  { id: 50, name: "Comoros", flag: "https://flagcdn.com/w40/km.png" },

  { id: 51, name: "Congo (DRC)", flag: "https://flagcdn.com/w40/cd.png" },
  { id: 52, name: "Congo (Republic)", flag: "https://flagcdn.com/w40/cg.png" },
  { id: 53, name: "Cook Islands", flag: "https://flagcdn.com/w40/ck.png" },
  { id: 54, name: "Costa Rica", flag: "https://flagcdn.com/w40/cr.png" },
  { id: 55, name: "Côte d’Ivoire", flag: "https://flagcdn.com/w40/ci.png" },
  { id: 56, name: "Croatia", flag: "https://flagcdn.com/w40/hr.png" },
  { id: 57, name: "Cuba", flag: "https://flagcdn.com/w40/cu.png" },
  { id: 58, name: "Curaçao", flag: "https://flagcdn.com/w40/cw.png" },
  { id: 59, name: "Cyprus", flag: "https://flagcdn.com/w40/cy.png" },
 { id: 60, name: "Czech Republic", flag: "https://flagcdn.com/w40/cz.png" },
  { id: 61, name: "Denmark", flag: "https://flagcdn.com/w40/dk.png" },
  { id: 62, name: "Djibouti", flag: "https://flagcdn.com/w40/dj.png" },
  { id: 63, name: "Dominica", flag: "https://flagcdn.com/w40/dm.png" },
  { id: 64, name: "Dominican Republic", flag: "https://flagcdn.com/w40/do.png" },
  { id: 65, name: "Ecuador", flag: "https://flagcdn.com/w40/ec.png" },
  { id: 66, name: "Egypt", flag: "https://flagcdn.com/w40/eg.png" },
  { id: 67, name: "El Salvador", flag: "https://flagcdn.com/w40/sv.png" },
  { id: 68, name: "Equatorial Guinea", flag: "https://flagcdn.com/w40/gq.png" },
  { id: 69, name: "Eritrea", flag: "https://flagcdn.com/w40/er.png" },
  { id: 70, name: "Estonia", flag: "https://flagcdn.com/w40/ee.png" },

  { id: 71, name: "Eswatini", flag: "https://flagcdn.com/w40/sz.png" },
  { id: 72, name: "Ethiopia", flag: "https://flagcdn.com/w40/et.png" },
  { id: 73, name: "Falkland Islands", flag: "https://flagcdn.com/w40/fk.png" },
  { id: 74, name: "Faroe Islands", flag: "https://flagcdn.com/w40/fo.png" },
  { id: 75, name: "Fiji", flag: "https://flagcdn.com/w40/fj.png" },
  { id: 76, name: "Finland", flag: "https://flagcdn.com/w40/fi.png" },
  { id: 77, name: "France", flag: "https://flagcdn.com/w40/fr.png" },
  { id: 78, name: "French Guiana", flag: "https://flagcdn.com/w40/gf.png" },
  { id: 79, name: "French Polynesia", flag: "https://flagcdn.com/w40/pf.png" },
  { id: 80, name: "French Southern Territories", flag: "https://flagcdn.com/w40/tf.png" },

  { id: 81, name: "Gabon", flag: "https://flagcdn.com/w40/ga.png" },
  { id: 82, name: "Gambia", flag: "https://flagcdn.com/w40/gm.png" },
  { id: 83, name: "Georgia", flag: "https://flagcdn.com/w40/ge.png" },
  { id: 84, name: "Germany", flag: "https://flagcdn.com/w40/de.png" },
  { id: 85, name: "Ghana", flag: "https://flagcdn.com/w40/gh.png" },
  { id: 86, name: "Gibraltar", flag: "https://flagcdn.com/w40/gi.png" },
  { id: 87, name: "Greece", flag: "https://flagcdn.com/w40/gr.png" },
  { id: 88, name: "Greenland", flag: "https://flagcdn.com/w40/gl.png" },
  { id: 89, name: "Grenada", flag: "https://flagcdn.com/w40/gd.png" },
  { id: 90, name: "Guadeloupe", flag: "https://flagcdn.com/w40/gp.png" },

  { id: 91, name: "Guam", flag: "https://flagcdn.com/w40/gu.png" },
  { id: 92, name: "Guatemala", flag: "https://flagcdn.com/w40/gt.png" },
  { id: 93, name: "Guernsey", flag: "https://flagcdn.com/w40/gg.png" },
  { id: 94, name: "Guinea", flag: "https://flagcdn.com/w40/gn.png" },
  { id: 95, name: "Guinea-Bissau", flag: "https://flagcdn.com/w40/gw.png" },
  { id: 96, name: "Guyana", flag: "https://flagcdn.com/w40/gy.png" },
  { id: 97, name: "Haiti", flag: "https://flagcdn.com/w40/ht.png" },
  { id: 98, name: "Heard Island and McDonald Islands", flag: "https://flagcdn.com/w40/hm.png" },
  { id: 99, name: "Holy See", flag: "https://flagcdn.com/w40/va.png" },
  { id: 100, name: "Honduras", flag: "https://flagcdn.com/w40/hn.png" },

  { id: 101, name: "Hong Kong", flag: "https://flagcdn.com/w40/hk.png" },
  { id: 102, name: "Hungary", flag: "https://flagcdn.com/w40/hu.png" },
  { id: 103, name: "Iceland", flag: "https://flagcdn.com/w40/is.png" },
  { id: 104, name: "India", flag: "https://flagcdn.com/w40/in.png" },
  { id: 105, name: "Indonesia", flag: "https://flagcdn.com/w40/id.png" },
  { id: 106, name: "Iran", flag: "https://flagcdn.com/w40/ir.png" },
  { id: 107, name: "Iraq", flag: "https://flagcdn.com/w40/iq.png" },
  { id: 108, name: "Ireland", flag: "https://flagcdn.com/w40/ie.png" },
  { id: 109, name: "Isle of Man", flag: "https://flagcdn.com/w40/im.png" },
  { id: 110, name: "Israel", flag: "https://flagcdn.com/w40/il.png" },

  { id: 111, name: "Italy", flag: "https://flagcdn.com/w40/it.png" },
  { id: 112, name: "Jamaica", flag: "https://flagcdn.com/w40/jm.png" },
  { id: 113, name: "Japan", flag: "https://flagcdn.com/w40/jp.png" },
  { id: 114, name: "Jersey", flag: "https://flagcdn.com/w40/je.png" },
  { id: 115, name: "Jordan", flag: "https://flagcdn.com/w40/jo.png" },
  { id: 116, name: "Kazakhstan", flag: "https://flagcdn.com/w40/kz.png" },
  { id: 117, name: "Kenya", flag: "https://flagcdn.com/w40/ke.png" },
  { id: 118, name: "Kiribati", flag: "https://flagcdn.com/w40/ki.png" },
  { id: 119, name: "Kuwait", flag: "https://flagcdn.com/w40/kw.png" },
  { id: 120, name: "Kyrgyzstan", flag: "https://flagcdn.com/w40/kg.png" },

  { id: 121, name: "Laos", flag: "https://flagcdn.com/w40/la.png" },
  { id: 122, name: "Latvia", flag: "https://flagcdn.com/w40/lv.png" },
  { id: 123, name: "Lebanon", flag: "https://flagcdn.com/w40/lb.png" },
  { id: 124, name: "Lesotho", flag: "https://flagcdn.com/w40/ls.png" },
  { id: 125, name: "Liberia", flag: "https://flagcdn.com/w40/lr.png" },
  { id: 126, name: "Libya", flag: "https://flagcdn.com/w40/ly.png" },
  { id: 127, name: "Liechtenstein", flag: "https://flagcdn.com/w40/li.png" },
  { id: 128, name: "Lithuania", flag: "https://flagcdn.com/w40/lt.png" },
  { id: 129, name: "Luxembourg", flag: "https://flagcdn.com/w40/lu.png" },
  { id: 130, name: "Macao", flag: "https://flagcdn.com/w40/mo.png" },

  { id: 131, name: "Madagascar", flag: "https://flagcdn.com/w40/mg.png" },
  { id: 132, name: "Malawi", flag: "https://flagcdn.com/w40/mw.png" },
  { id: 133, name: "Malaysia", flag: "https://flagcdn.com/w40/my.png" },
  { id: 134, name: "Maldives", flag: "https://flagcdn.com/w40/mv.png" },
  { id: 135, name: "Mali", flag: "https://flagcdn.com/w40/ml.png" },
  { id: 136, name: "Malta", flag: "https://flagcdn.com/w40/mt.png" },
  { id: 137, name: "Marshall Islands", flag: "https://flagcdn.com/w40/mh.png" },
  { id: 138, name: "Martinique", flag: "https://flagcdn.com/w40/mq.png" },
  { id: 139, name: "Mauritania", flag: "https://flagcdn.com/w40/mr.png" },
  { id: 140, name: "Mauritius", flag: "https://flagcdn.com/w40/mu.png" },

  { id: 141, name: "Mayotte", flag: "https://flagcdn.com/w40/yt.png" },
  { id: 142, name: "Mexico", flag: "https://flagcdn.com/w40/mx.png" },
  { id: 143, name: "Micronesia", flag: "https://flagcdn.com/w40/fm.png" },
  { id: 144, name: "Moldova", flag: "https://flagcdn.com/w40/md.png" },
  { id: 145, name: "Monaco", flag: "https://flagcdn.com/w40/mc.png" },
  { id: 146, name: "Mongolia", flag: "https://flagcdn.com/w40/mn.png" },
  { id: 147, name: "Montenegro", flag: "https://flagcdn.com/w40/me.png" },
  { id: 148, name: "Montserrat", flag: "https://flagcdn.com/w40/ms.png" },
  { id: 149, name: "Morocco", flag: "https://flagcdn.com/w40/ma.png" },
  { id: 150, name: "Mozambique", flag: "https://flagcdn.com/w40/mz.png" },

  { id: 151, name: "Myanmar", flag: "https://flagcdn.com/w40/mm.png" },
  { id: 152, name: "Namibia", flag: "https://flagcdn.com/w40/na.png" },
  { id: 153, name: "Nauru", flag: "https://flagcdn.com/w40/nr.png" },
  { id: 154, name: "Nepal", flag: "https://flagcdn.com/w40/np.png" },
  { id: 155, name: "Netherlands", flag: "https://flagcdn.com/w40/nl.png" },
  { id: 156, name: "New Caledonia", flag: "https://flagcdn.com/w40/nc.png" },
  { id: 157, name: "New Zealand", flag: "https://flagcdn.com/w40/nz.png" },
  { id: 158, name: "Nicaragua", flag: "https://flagcdn.com/w40/ni.png" },
  { id: 159, name: "Niger", flag: "https://flagcdn.com/w40/ne.png" },
  { id: 160, name: "Nigeria", flag: "https://flagcdn.com/w40/ng.png" },
  { id: 161, name: "North Macedonia", flag: "https://flagcdn.com/w40/mk.png" },
  { id: 162, name: "Norway", flag: "https://flagcdn.com/w40/no.png" },
  { id: 163, name: "Oman", flag: "https://flagcdn.com/w40/om.png" },
  { id: 164, name: "Pakistan", flag: "https://flagcdn.com/w40/pk.png" },
  { id: 165, name: "Palau", flag: "https://flagcdn.com/w40/pw.png" },
  { id: 166, name: "Palestine", flag: "https://flagcdn.com/w40/ps.png" },
  { id: 167, name: "Panama", flag: "https://flagcdn.com/w40/pa.png" },
  { id: 168, name: "Papua New Guinea", flag: "https://flagcdn.com/w40/pg.png" },
  { id: 169, name: "Paraguay", flag: "https://flagcdn.com/w40/py.png" },
  { id: 170, name: "Peru", flag: "https://flagcdn.com/w40/pe.png" },

  { id: 171, name: "Philippines", flag: "https://flagcdn.com/w40/ph.png" },
  { id: 172, name: "Pitcairn Islands", flag: "https://flagcdn.com/w40/pn.png" },
  { id: 173, name: "Poland", flag: "https://flagcdn.com/w40/pl.png" },
  { id: 174, name: "Portugal", flag: "https://flagcdn.com/w40/pt.png" },
  { id: 175, name: "Puerto Rico", flag: "https://flagcdn.com/w40/pr.png" },
  { id: 176, name: "Qatar", flag: "https://flagcdn.com/w40/qa.png" },
  { id: 177, name: "Réunion", flag: "https://flagcdn.com/w40/re.png" },
  { id: 178, name: "Romania", flag: "https://flagcdn.com/w40/ro.png" },
  { id: 179, name: "Russia", flag: "https://flagcdn.com/w40/ru.png" },
  { id: 180, name: "Rwanda", flag: "https://flagcdn.com/w40/rw.png" },

  { id: 181, name: "Saint Barthélemy", flag: "https://flagcdn.com/w40/bl.png" },
  { id: 182, name: "Saint Helena, Ascension and Tristan da Cunha", flag: "https://flagcdn.com/w40/sh.png" },
  { id: 183, name: "Saint Kitts and Nevis", flag: "https://flagcdn.com/w40/kn.png" },
  { id: 184, name: "Saint Lucia", flag: "https://flagcdn.com/w40/lc.png" },
  { id: 185, name: "Saint Martin", flag: "https://flagcdn.com/w40/mf.png" },
  { id: 186, name: "Saint Pierre and Miquelon", flag: "https://flagcdn.com/w40/pm.png" },
  { id: 187, name: "Saint Vincent and the Grenadines", flag: "https://flagcdn.com/w40/vc.png" },
  { id: 188, name: "Samoa", flag: "https://flagcdn.com/w40/ws.png" },
  { id: 189, name: "San Marino", flag: "https://flagcdn.com/w40/sm.png" },
  { id: 190, name: "Sao Tome and Principe", flag: "https://flagcdn.com/w40/st.png" },

  { id: 191, name: "Saudi Arabia", flag: "https://flagcdn.com/w40/sa.png" },
  { id: 192, name: "Senegal", flag: "https://flagcdn.com/w40/sn.png" },
  { id: 193, name: "Serbia", flag: "https://flagcdn.com/w40/rs.png" },
  { id: 194, name: "Seychelles", flag: "https://flagcdn.com/w40/sc.png" },
  { id: 195, name: "Sierra Leone", flag: "https://flagcdn.com/w40/sl.png" },
  { id: 196, name: "Singapore", flag: "https://flagcdn.com/w40/sg.png" },
  { id: 197, name: "Sint Maarten", flag: "https://flagcdn.com/w40/sx.png" },
  { id: 198, name: "Slovakia", flag: "https://flagcdn.com/w40/sk.png" },
  { id: 199, name: "Slovenia", flag: "https://flagcdn.com/w40/si.png" },
  { id: 200, name: "Solomon Islands", flag: "https://flagcdn.com/w40/sb.png" },

  { id: 201, name: "Somalia", flag: "https://flagcdn.com/w40/so.png" },
  { id: 202, name: "South Africa", flag: "https://flagcdn.com/w40/za.png" },
  { id: 203, name: "South Georgia and the South Sandwich Islands", flag: "https://flagcdn.com/w40/gs.png" },
  { id: 204, name: "South Korea", flag: "https://flagcdn.com/w40/kr.png" },
  { id: 205, name: "South Sudan", flag: "https://flagcdn.com/w40/ss.png" },
  { id: 206, name: "Spain", flag: "https://flagcdn.com/w40/es.png" },
  { id: 207, name: "Sri Lanka", flag: "https://flagcdn.com/w40/lk.png" },
  { id: 208, name: "Sudan", flag: "https://flagcdn.com/w40/sd.png" },
  { id: 209, name: "Suriname", flag: "https://flagcdn.com/w40/sr.png" },
  { id: 210, name: "Svalbard and Jan Mayen", flag: "https://flagcdn.com/w40/sj.png" },

  { id: 211, name: "Sweden", flag: "https://flagcdn.com/w40/se.png" },
  { id: 212, name: "Switzerland", flag: "https://flagcdn.com/w40/ch.png" },
  { id: 213, name: "Syria", flag: "https://flagcdn.com/w40/sy.png" },
  { id: 214, name: "Taiwan", flag: "https://flagcdn.com/w40/tw.png" },
  { id: 215, name: "Tajikistan", flag: "https://flagcdn.com/w40/tj.png" },
  { id: 216, name: "Tanzania", flag: "https://flagcdn.com/w40/tz.png" },
  { id: 217, name: "Thailand", flag: "https://flagcdn.com/w40/th.png" },
  { id: 218, name: "Timor-Leste", flag: "https://flagcdn.com/w40/tl.png" },
  { id: 219, name: "Togo", flag: "https://flagcdn.com/w40/tg.png" },
  { id: 220, name: "Tokelau", flag: "https://flagcdn.com/w40/tk.png" },

  { id: 221, name: "Tonga", flag: "https://flagcdn.com/w40/to.png" },
  { id: 222, name: "Trinidad and Tobago", flag: "https://flagcdn.com/w40/tt.png" },
  { id: 223, name: "Tunisia", flag: "https://flagcdn.com/w40/tn.png" },
  { id: 224, name: "Turkey", flag: "https://flagcdn.com/w40/tr.png" },
  { id: 225, name: "Turkmenistan", flag: "https://flagcdn.com/w40/tm.png" },
  { id: 226, name: "Tuvalu", flag: "https://flagcdn.com/w40/tv.png" },
  { id: 227, name: "Uganda", flag: "https://flagcdn.com/w40/ug.png" },
  { id: 228, name: "Ukraine", flag: "https://flagcdn.com/w40/ua.png" },
  { id: 229, name: "United Arab Emirates", flag: "https://flagcdn.com/w40/ae.png" },
  { id: 230, name: "United Kingdom", flag: "https://flagcdn.com/w40/gb.png" },

  { id: 231, name: "United States", flag: "https://flagcdn.com/w40/us.png" },
  { id: 232, name: "Uruguay", flag: "https://flagcdn.com/w40/uy.png" },
  { id: 233, name: "Uzbekistan", flag: "https://flagcdn.com/w40/uz.png" },
  { id: 234, name: "Vanuatu", flag: "https://flagcdn.com/w40/vu.png" },
  { id: 235, name: "Venezuela", flag: "https://flagcdn.com/w40/ve.png" },
  { id: 236, name: "Vietnam", flag: "https://flagcdn.com/w40/vn.png" },
  { id: 237, name: "British Virgin Islands", flag: "https://flagcdn.com/w40/vg.png" },
  { id: 238, name: "U.S. Virgin Islands", flag: "https://flagcdn.com/w40/vi.png" },
  { id: 239, name: "Wallis and Futuna", flag: "https://flagcdn.com/w40/wf.png" },
  { id: 240, name: "Western Sahara", flag: "https://flagcdn.com/w40/eh.png" },

  { id: 241, name: "Yemen", flag: "https://flagcdn.com/w40/ye.png" },
  { id: 242, name: "Zambia", flag: "https://flagcdn.com/w40/zm.png" },
  { id: 243, name: "Zimbabwe", flag: "https://flagcdn.com/w40/zw.png" },
  { id: 244, name: "Kosovo", flag: "https://flagcdn.com/w40/xk.png" },
  { id: 245, name: "Somaliland", flag: "https://flagcdn.com/w40/so.png" }, // unofficial
  { id: 246, name: "Taiwan (Republic of China)", flag: "https://flagcdn.com/w40/tw.png" }, // duplicate for clarity
  { id: 247, name: "Palestine", flag: "https://flagcdn.com/w40/ps.png" }, // duplicate for clarity
  { id: 248, name: "South Ossetia", flag: "https://flagcdn.com/w40/rs.png" }, // unofficial
  { id: 249, name: "Abkhazia", flag: "https://flagcdn.com/w40/ge.png" }, // unofficial
];
//Arabic content
const arabic = {
   edit: "تعديل",
  myJobs: "وظائفي",
    createJob: "إنشاء وظيفة",
    proposals: "المقترحات",
    create: "إنشاء",
  alreadySignedInMessage:"أنت مسجل دخولك بالفعل",
  organizationName: "اسم المؤسسة",
  donhave: "ليس لديك حساب؟",
  createOne: "أنشئ حسابًا",
  notMemeber:"لست عضوًا؟",
  password: "كلمة المرور",
  signUp: "إنشاء حساب",
  fname: "الاسم الأول",
  lname: "اسم العائلة",
  email: "البريد الإلكتروني",
  role: "الدور",
  employee: "موظف",
  employer: "صاحب عمل",
  haveAccount: "هل لديك حساب بالفعل؟",
  logIn: "تسجيل الدخول",
  home_link: "الرئيسية",
  sent_link: "طلبات التوظيف",
  saved_link: "المحفوظات",
  explore_link: "استكشف",
  dashboard_link: "لوحة التحكم",
  find_job: "ابحث عن وظيفة",
  apply:"يتقدم",
  hero_header: "ابدأ مستقبلك مع الوظيفة المثالية",
  hero_paragraph:
    "تصفح آلاف الوظائف، قدّم في ثوانٍ، واحصل على الفرصة التي تستحقها.",

  job_posted: "الوظائف المنشورة",
  active_users: "الباحثون عن عمل النشطون",
  campany_amount: "الشركات التي توظّف",

  motive_header: "أفضل طريقة للحصول على وظيفة",
  motive_paragraph:
    "حوّل كل طلب توظيف إلى فرصة حقيقية من خلال إرشادات الخبراء في بناء العلاقات، وبناء العلامة الشخصية، وإتقان المقابلات.",

  about_us: "من نحن",
  about_paragraph:
    "Jobify هي منظمة مستقلة ومحايدة تربط أصحاب العمل بالباحثين عن عمل حول العالم. تأسست عام 2026 على يد Bereket Girma، وتعمل Jobify في أكثر من 80 دولة، مما يسهّل التوظيف والبحث عن عمل عبر منصة موثوقة وسهلة الاستخدام.",

  staf_header: "مجتمعنا",

  footer_paragraph:
    "تربط Jobify الباحثين عن عمل بأفضل الفرص حول العالم. قدّم خلال ثوانٍ واحصل على وظيفة أحلامك.",

  quick_link: "روابط سريعة",
  about: "حول",

  footer_about_paragraph: `تأسست عام 2026 على يد Bereket Girma، وتعمل Jobify في أكثر من 80 دولة،
            مما يسهّل التوظيف والبحث عن عمل.`,

  learn_more: "اعرف المزيد",
  contact: "تواصل معنا",
  phone: "الهاتف",
  right: " جميع الحقوق محفوظة.",
  links: "روابط سريعة",
  categories: "الفئات",
  location: "الموقع",
  jobType: "نوع الوظيفة",
  salary: "الدخل",

  jobSearchPlaceholder: "ابحث عن وظيفة",
  proposalPlaceholder: "أدخل تفاصيل العرض...",
  writeProposal: "كتابة العرض",
  markdownSupport: "يدعم تنسيق Markdown",

  headline: "احصل على وظيفتك المثالية",
  careers: "المسارات المهنية",
  below: "أدناه",
  send: "إرسال",

  dashboard: "لوحة التحكم",
  workspace: "مساحة العمل",
  inbox: "صندوق الوارد",

  name: "الاسم",
  post: "نشر",
  team: "فريقنا",

  aboutJob: "حول الوظيفة",
  signOut: "تسجيل الخروج",
  jobDetails: "تفاصيل الوظيفة",
  title: "العنوان",
  language: "اللغة",
};
const teamsAr = [
  {
    name: "Oliver Benjamin",
    img: "/photo-1560250097-0b93528c311a.avif",
    description:
      "قيادة الاستراتيجية والرؤية لتوسيع منصات التوظيف المعتمدة على الذكاء الاصطناعي",
    stars: 4.5,
    halfStar: true,
    color: "bg-sky-600",
    title: "الرئيس التنفيذي",
  },
  {
    name: "Emily Grace",
    img: "/photo-1494790108377-be9c29b29330.avif",
    description:
      "إدارة الفرق وعمليات التنفيذ لضمان تشغيل موثوق ومستقر",
    stars: 5,
    halfStar: false,
    color: "bg-pink-500",
    title: "قائدة الفريق",
  },
  {
    name: "Alexander Carter",
    img: "/photo-1599566150163-29194dcaad36.avif",
    description:
      "الإشراف على التخطيط المالي والامتثال والنمو طويل الأمد",
    stars: 5,
    halfStar: false,
    color: "bg-green-500",
    title: "المدير المالي",
  },
  {
    name: "Thomas Anderson",
    img: "/premium_photo-1689539137236-b68e436248de.avif",
    description:
      "دعم المهام اليومية والتنسيق وضمان سلاسة سير العمليات الأساسية",
    stars: 3,
    halfStar: true,
    color: "bg-yellow-500",
    title: "مساعد",
  },
];
const categoriesAr = [
  { id: 1, name: "الرعاية الصحية والطبية" },
  { id: 2, name: "تكنولوجيا المعلومات (IT) والبرمجيات" },
  { id: 3, name: "التعليم والتدريس" },
  { id: 4, name: "الهندسة والفنون التقنية" },
  { id: 5, name: "المالية والمحاسبة" },
  { id: 6, name: "المبيعات والتسويق" },
  { id: 7, name: "الموارد البشرية والإدارة" },
  { id: 8, name: "الإبداع والتصميم" },
  { id: 9, name: "الضيافة والسياحة" },
  { id: 10, name: "التصنيع والحرف" },
];
const jobTypesAr = [
  { id: 1, name: "دوام كامل" },
  { id: 2, name: "دوام جزئي" },
  { id: 3, name: "عقد" },
  { id: 4, name: "مؤقت" },
  { id: 5, name: "تدريب" },
  { id: 6, name: "عمل حر / مستقل" },
  { id: 7, name: "عن بُعد" },
  { id: 8, name: "مختلط" },
  { id: 9, name: "في الموقع" },
  { id: 10, name: "موسمي" },
  { id: 11, name: "متطوع" },
  { id: 12, name: "تدريب مهني" },
];
const countriesAr: countriesType[] = [
  { id: 1, name: "أفغانستان", flag: "https://flagcdn.com/w40/af.png" },
  { id: 2, name: "جزر آلاند", flag: "https://flagcdn.com/w40/ax.png" },
  { id: 3, name: "ألبانيا", flag: "https://flagcdn.com/w40/al.png" },
  { id: 4, name: "الجزائر", flag: "https://flagcdn.com/w40/dz.png" },
  { id: 5, name: "ساموا الأمريكية", flag: "https://flagcdn.com/w40/as.png" },
  { id: 6, name: "أندورا", flag: "https://flagcdn.com/w40/ad.png" },
  { id: 7, name: "أنغولا", flag: "https://flagcdn.com/w40/ao.png" },
  { id: 8, name: "أنغيلا", flag: "https://flagcdn.com/w40/ai.png" },
  { id: 9, name: "أنتاركتيكا", flag: "https://flagcdn.com/w40/aq.png" },
  { id: 10, name: "أنتيغوا وباربودا", flag: "https://flagcdn.com/w40/ag.png" },

  { id: 11, name: "الأرجنتين", flag: "https://flagcdn.com/w40/ar.png" },
  { id: 12, name: "أرمينيا", flag: "https://flagcdn.com/w40/am.png" },
  { id: 13, name: "أروبا", flag: "https://flagcdn.com/w40/aw.png" },
  { id: 14, name: "أستراليا", flag: "https://flagcdn.com/w40/au.png" },
  { id: 15, name: "النمسا", flag: "https://flagcdn.com/w40/at.png" },
  { id: 16, name: "أذربيجان", flag: "https://flagcdn.com/w40/az.png" },
  { id: 17, name: "الباهاماس", flag: "https://flagcdn.com/w40/bs.png" },
  { id: 18, name: "البحرين", flag: "https://flagcdn.com/w40/bh.png" },
  { id: 19, name: "بنغلاديش", flag: "https://flagcdn.com/w40/bd.png" },
  { id: 20, name: "بربادوس", flag: "https://flagcdn.com/w40/bb.png" },

  { id: 21, name: "بيلاروسيا", flag: "https://flagcdn.com/w40/by.png" },
  { id: 22, name: "بلجيكا", flag: "https://flagcdn.com/w40/be.png" },
  { id: 23, name: "بيليز", flag: "https://flagcdn.com/w40/bz.png" },
  { id: 24, name: "بنن", flag: "https://flagcdn.com/w40/bj.png" },
  { id: 25, name: "برمودا", flag: "https://flagcdn.com/w40/bm.png" },
  { id: 26, name: "بوتان", flag: "https://flagcdn.com/w40/bt.png" },
  { id: 27, name: "بوليفيا", flag: "https://flagcdn.com/w40/bo.png" },
  { id: 28, name: "بونير، سينت أوستاتيوس وسابا", flag: "https://flagcdn.com/w40/bq.png" },
  { id: 29, name: "البوسنة والهرسك", flag: "https://flagcdn.com/w40/ba.png" },
  { id: 30, name: "بوتسوانا", flag: "https://flagcdn.com/w40/bw.png" },

  { id: 31, name: "جزيرة بوفيه", flag: "https://flagcdn.com/w40/bv.png" },
  { id: 32, name: "البرازيل", flag: "https://flagcdn.com/w40/br.png" },
  { id: 33, name: "إقليم المحيط الهندي البريطاني", flag: "https://flagcdn.com/w40/io.png" },
  { id: 34, name: "بروناي", flag: "https://flagcdn.com/w40/bn.png" },
  { id: 35, name: "بلغاريا", flag: "https://flagcdn.com/w40/bg.png" },
  { id: 36, name: "بوركينا فاسو", flag: "https://flagcdn.com/w40/bf.png" },
  { id: 37, name: "بوروندي", flag: "https://flagcdn.com/w40/bi.png" },
  { id: 38, name: "الرأس الأخضر", flag: "https://flagcdn.com/w40/cv.png" },
  { id: 39, name: "كمبوديا", flag: "https://flagcdn.com/w40/kh.png" },
  { id: 40, name: "الكاميرون", flag: "https://flagcdn.com/w40/cm.png" },

  { id: 41, name: "كندا", flag: "https://flagcdn.com/w40/ca.png" },
  { id: 42, name: "جزر كايمان", flag: "https://flagcdn.com/w40/ky.png" },
  { id: 43, name: "جمهورية أفريقيا الوسطى", flag: "https://flagcdn.com/w40/cf.png" },
  { id: 44, name: "تشاد", flag: "https://flagcdn.com/w40/td.png" },
  { id: 45, name: "تشيلي", flag: "https://flagcdn.com/w40/cl.png" },
  { id: 46, name: "الصين", flag: "https://flagcdn.com/w40/cn.png" },
  { id: 47, name: "جزيرة عيد الميلاد", flag: "https://flagcdn.com/w40/cx.png" },
  { id: 48, name: "جزر كوكوس (كيلينغ)", flag: "https://flagcdn.com/w40/cc.png" },
  { id: 49, name: "كولومبيا", flag: "https://flagcdn.com/w40/co.png" },
  { id: 50, name: "جزر القمر", flag: "https://flagcdn.com/w40/km.png" },

  { id: 51, name: "جمهورية الكونغو الديمقراطية", flag: "https://flagcdn.com/w40/cd.png" },
  { id: 52, name: "جمهورية الكونغو", flag: "https://flagcdn.com/w40/cg.png" },
  { id: 53, name: "جزر كوك", flag: "https://flagcdn.com/w40/ck.png" },
  { id: 54, name: "كوستاريكا", flag: "https://flagcdn.com/w40/cr.png" },
  { id: 55, name: "ساحل العاج", flag: "https://flagcdn.com/w40/ci.png" },
  { id: 56, name: "كرواتيا", flag: "https://flagcdn.com/w40/hr.png" },
  { id: 57, name: "كوبا", flag: "https://flagcdn.com/w40/cu.png" },
  { id: 58, name: "كوراساو", flag: "https://flagcdn.com/w40/cw.png" },
  { id: 59, name: "قبرص", flag: "https://flagcdn.com/w40/cy.png" },
  { id: 60, name: "جمهورية التشيك", flag: "https://flagcdn.com/w40/cz.png" },
{ id: 61, name: "الدنمارك", flag: "https://flagcdn.com/w40/dk.png" },
  { id: 62, name: "جيبوتي", flag: "https://flagcdn.com/w40/dj.png" },
  { id: 63, name: "دومينيكا", flag: "https://flagcdn.com/w40/dm.png" },
  { id: 64, name: "جمهورية الدومينيكان", flag: "https://flagcdn.com/w40/do.png" },
  { id: 65, name: "الإكوادور", flag: "https://flagcdn.com/w40/ec.png" },
  { id: 66, name: "مصر", flag: "https://flagcdn.com/w40/eg.png" },
  { id: 67, name: "السلفادور", flag: "https://flagcdn.com/w40/sv.png" },
  { id: 68, name: "غينيا الاستوائية", flag: "https://flagcdn.com/w40/gq.png" },
  { id: 69, name: "إريتريا", flag: "https://flagcdn.com/w40/er.png" },
  { id: 70, name: "إستونيا", flag: "https://flagcdn.com/w40/ee.png" },

  { id: 71, name: "إسواتيني", flag: "https://flagcdn.com/w40/sz.png" },
  { id: 72, name: "إثيوبيا", flag: "https://flagcdn.com/w40/et.png" },
  { id: 73, name: "جزر فوكلاند", flag: "https://flagcdn.com/w40/fk.png" },
  { id: 74, name: "جزر فارو", flag: "https://flagcdn.com/w40/fo.png" },
  { id: 75, name: "فيجي", flag: "https://flagcdn.com/w40/fj.png" },
  { id: 76, name: "فنلندا", flag: "https://flagcdn.com/w40/fi.png" },
  { id: 77, name: "فرنسا", flag: "https://flagcdn.com/w40/fr.png" },
  { id: 78, name: "غيانا الفرنسية", flag: "https://flagcdn.com/w40/gf.png" },
  { id: 79, name: "بولينيزيا الفرنسية", flag: "https://flagcdn.com/w40/pf.png" },
  { id: 80, name: "الأقاليم الجنوبية الفرنسية", flag: "https://flagcdn.com/w40/tf.png" },

  { id: 81, name: "الغابون", flag: "https://flagcdn.com/w40/ga.png" },
  { id: 82, name: "غامبيا", flag: "https://flagcdn.com/w40/gm.png" },
  { id: 83, name: "جورجيا", flag: "https://flagcdn.com/w40/ge.png" },
  { id: 84, name: "ألمانيا", flag: "https://flagcdn.com/w40/de.png" },
  { id: 85, name: "غانا", flag: "https://flagcdn.com/w40/gh.png" },
  { id: 86, name: "جبل طارق", flag: "https://flagcdn.com/w40/gi.png" },
  { id: 87, name: "اليونان", flag: "https://flagcdn.com/w40/gr.png" },
  { id: 88, name: "جرينلاند", flag: "https://flagcdn.com/w40/gl.png" },
  { id: 89, name: "جرينادا", flag: "https://flagcdn.com/w40/gd.png" },
  { id: 90, name: "جوادلوب", flag: "https://flagcdn.com/w40/gp.png" },

  { id: 91, name: "غوام", flag: "https://flagcdn.com/w40/gu.png" },
  { id: 92, name: "غواتيمالا", flag: "https://flagcdn.com/w40/gt.png" },
  { id: 93, name: "غيرنزي", flag: "https://flagcdn.com/w40/gg.png" },
  { id: 94, name: "غينيا", flag: "https://flagcdn.com/w40/gn.png" },
  { id: 95, name: "غينيا بيساو", flag: "https://flagcdn.com/w40/gw.png" },
  { id: 96, name: "غيانا", flag: "https://flagcdn.com/w40/gy.png" },
  { id: 97, name: "هايتي", flag: "https://flagcdn.com/w40/ht.png" },
  { id: 98, name: "جزيرة هيرد وجزر ماكدونالد", flag: "https://flagcdn.com/w40/hm.png" },
  { id: 99, name: "الكرسي الرسولي (الفاتيكان)", flag: "https://flagcdn.com/w40/va.png" },
  { id: 100, name: "هندوراس", flag: "https://flagcdn.com/w40/hn.png" },

  { id: 101, name: "هونغ كونغ", flag: "https://flagcdn.com/w40/hk.png" },
  { id: 102, name: "المجر", flag: "https://flagcdn.com/w40/hu.png" },
  { id: 103, name: "آيسلندا", flag: "https://flagcdn.com/w40/is.png" },
  { id: 104, name: "الهند", flag: "https://flagcdn.com/w40/in.png" },
  { id: 105, name: "إندونيسيا", flag: "https://flagcdn.com/w40/id.png" },
  { id: 106, name: "إيران", flag: "https://flagcdn.com/w40/ir.png" },
  { id: 107, name: "العراق", flag: "https://flagcdn.com/w40/iq.png" },
  { id: 108, name: "أيرلندا", flag: "https://flagcdn.com/w40/ie.png" },
  { id: 109, name: "جزيرة مان", flag: "https://flagcdn.com/w40/im.png" },
  { id: 110, name: "إسرائيل", flag: "https://flagcdn.com/w40/il.png" },

  { id: 111, name: "إيطاليا", flag: "https://flagcdn.com/w40/it.png" },
  { id: 112, name: "جامايكا", flag: "https://flagcdn.com/w40/jm.png" },
  { id: 113, name: "اليابان", flag: "https://flagcdn.com/w40/jp.png" },
  { id: 114, name: "جيرسي", flag: "https://flagcdn.com/w40/je.png" },
  { id: 115, name: "الأردن", flag: "https://flagcdn.com/w40/jo.png" },
  { id: 116, name: "كازاخستان", flag: "https://flagcdn.com/w40/kz.png" },
  { id: 117, name: "كينيا", flag: "https://flagcdn.com/w40/ke.png" },
  { id: 118, name: "كيريباتي", flag: "https://flagcdn.com/w40/ki.png" },
  { id: 119, name: "الكويت", flag: "https://flagcdn.com/w40/kw.png" },
  { id: 120, name: "قيرغيزستان", flag: "https://flagcdn.com/w40/kg.png" },

  { id: 121, name: "لاوس", flag: "https://flagcdn.com/w40/la.png" },
  { id: 122, name: "لاتفيا", flag: "https://flagcdn.com/w40/lv.png" },
  { id: 123, name: "لبنان", flag: "https://flagcdn.com/w40/lb.png" },
  { id: 124, name: "ليسوتو", flag: "https://flagcdn.com/w40/ls.png" },
  { id: 125, name: "ليبيريا", flag: "https://flagcdn.com/w40/lr.png" },
  { id: 126, name: "ليبيا", flag: "https://flagcdn.com/w40/ly.png" },
  { id: 127, name: "ليختنشتاين", flag: "https://flagcdn.com/w40/li.png" },
  { id: 128, name: "ليتوانيا", flag: "https://flagcdn.com/w40/lt.png" },
  { id: 129, name: "لوكسمبورغ", flag: "https://flagcdn.com/w40/lu.png" },
  { id: 130, name: "ماكاو", flag: "https://flagcdn.com/w40/mo.png" },

  { id: 131, name: "مدغشقر", flag: "https://flagcdn.com/w40/mg.png" },
  { id: 132, name: "مالاوي", flag: "https://flagcdn.com/w40/mw.png" },
  { id: 133, name: "ماليزيا", flag: "https://flagcdn.com/w40/my.png" },
  { id: 134, name: "جزر المالديف", flag: "https://flagcdn.com/w40/mv.png" },
  { id: 135, name: "مالي", flag: "https://flagcdn.com/w40/ml.png" },
  { id: 136, name: "مالطا", flag: "https://flagcdn.com/w40/mt.png" },
  { id: 137, name: "جزر مارشال", flag: "https://flagcdn.com/w40/mh.png" },
  { id: 138, name: "مارتينيك", flag: "https://flagcdn.com/w40/mq.png" },
  { id: 139, name: "موريتانيا", flag: "https://flagcdn.com/w40/mr.png" },
  { id: 140, name: "موريشيوس", flag: "https://flagcdn.com/w40/mu.png" },

  { id: 141, name: "مايوت", flag: "https://flagcdn.com/w40/yt.png" },
  { id: 142, name: "المكسيك", flag: "https://flagcdn.com/w40/mx.png" },
  { id: 143, name: "ميكرونيزيا", flag: "https://flagcdn.com/w40/fm.png" },
  { id: 144, name: "مولدوفا", flag: "https://flagcdn.com/w40/md.png" },
  { id: 145, name: "موناكو", flag: "https://flagcdn.com/w40/mc.png" },
  { id: 146, name: "منغوليا", flag: "https://flagcdn.com/w40/mn.png" },
  { id: 147, name: "مونتينيغرو", flag: "https://flagcdn.com/w40/me.png" },
  { id: 148, name: "مونتسرات", flag: "https://flagcdn.com/w40/ms.png" },
  { id: 149, name: "المغرب", flag: "https://flagcdn.com/w40/ma.png" },
  { id: 150, name: "موزمبيق", flag: "https://flagcdn.com/w40/mz.png" },

  { id: 151, name: "ميانمار", flag: "https://flagcdn.com/w40/mm.png" },
  { id: 152, name: "ناميبيا", flag: "https://flagcdn.com/w40/na.png" },
  { id: 153, name: "ناورو", flag: "https://flagcdn.com/w40/nr.png" },
  { id: 154, name: "نيبال", flag: "https://flagcdn.com/w40/np.png" },
  { id: 155, name: "هولندا", flag: "https://flagcdn.com/w40/nl.png" },
  { id: 156, name: "كاليدونيا الجديدة", flag: "https://flagcdn.com/w40/nc.png" },
  { id: 157, name: "نيوزيلندا", flag: "https://flagcdn.com/w40/nz.png" },
  { id: 158, name: "نيكاراغوا", flag: "https://flagcdn.com/w40/ni.png" },
  { id: 159, name: "النيجر", flag: "https://flagcdn.com/w40/ne.png" },
  { id: 160, name: "نيجيريا", flag: "https://flagcdn.com/w40/ng.png" },
 { id: 161, name: "مقدونيا الشمالية", flag: "https://flagcdn.com/w40/mk.png" },
  { id: 162, name: "النرويج", flag: "https://flagcdn.com/w40/no.png" },
  { id: 163, name: "عمان", flag: "https://flagcdn.com/w40/om.png" },
  { id: 164, name: "باكستان", flag: "https://flagcdn.com/w40/pk.png" },
  { id: 165, name: "بالاو", flag: "https://flagcdn.com/w40/pw.png" },
  { id: 166, name: "فلسطين", flag: "https://flagcdn.com/w40/ps.png" },
  { id: 167, name: "بنما", flag: "https://flagcdn.com/w40/pa.png" },
  { id: 168, name: "بابوا غينيا الجديدة", flag: "https://flagcdn.com/w40/pg.png" },
  { id: 169, name: "باراغواي", flag: "https://flagcdn.com/w40/py.png" },
  { id: 170, name: "بيرو", flag: "https://flagcdn.com/w40/pe.png" },

  { id: 171, name: "الفلبين", flag: "https://flagcdn.com/w40/ph.png" },
  { id: 172, name: "جزر بيتكيرن", flag: "https://flagcdn.com/w40/pn.png" },
  { id: 173, name: "بولندا", flag: "https://flagcdn.com/w40/pl.png" },
  { id: 174, name: "البرتغال", flag: "https://flagcdn.com/w40/pt.png" },
  { id: 175, name: "بورتو ريكو", flag: "https://flagcdn.com/w40/pr.png" },
  { id: 176, name: "قطر", flag: "https://flagcdn.com/w40/qa.png" },
  { id: 177, name: "لا ريونيون", flag: "https://flagcdn.com/w40/re.png" },
  { id: 178, name: "رومانيا", flag: "https://flagcdn.com/w40/ro.png" },
  { id: 179, name: "روسيا", flag: "https://flagcdn.com/w40/ru.png" },
  { id: 180, name: "رواندا", flag: "https://flagcdn.com/w40/rw.png" },

  { id: 181, name: "سانت بارتيلمي", flag: "https://flagcdn.com/w40/bl.png" },
  { id: 182, name: "سانت هيلانة وأسنسيو وتريستان دا كونا", flag: "https://flagcdn.com/w40/sh.png" },
  { id: 183, name: "سانت كيتس ونيفيس", flag: "https://flagcdn.com/w40/kn.png" },
  { id: 184, name: "سانت لوسيا", flag: "https://flagcdn.com/w40/lc.png" },
  { id: 185, name: "سانت مارتن", flag: "https://flagcdn.com/w40/mf.png" },
  { id: 186, name: "سانت بيير وميكلون", flag: "https://flagcdn.com/w40/pm.png" },
  { id: 187, name: "سانت فنسنت وجزر غرينادين", flag: "https://flagcdn.com/w40/vc.png" },
  { id: 188, name: "ساموا", flag: "https://flagcdn.com/w40/ws.png" },
  { id: 189, name: "سان مارينو", flag: "https://flagcdn.com/w40/sm.png" },
  { id: 190, name: "ساو تومي وبرينسيبي", flag: "https://flagcdn.com/w40/st.png" },

  { id: 191, name: "المملكة العربية السعودية", flag: "https://flagcdn.com/w40/sa.png" },
  { id: 192, name: "السنغال", flag: "https://flagcdn.com/w40/sn.png" },
  { id: 193, name: "صربيا", flag: "https://flagcdn.com/w40/rs.png" },
  { id: 194, name: "سيشل", flag: "https://flagcdn.com/w40/sc.png" },
  { id: 195, name: "سيراليون", flag: "https://flagcdn.com/w40/sl.png" },
  { id: 196, name: "سنغافورة", flag: "https://flagcdn.com/w40/sg.png" },
  { id: 197, name: "سينت مارتن (جزء هولندي)", flag: "https://flagcdn.com/w40/sx.png" },
  { id: 198, name: "سلوفاكيا", flag: "https://flagcdn.com/w40/sk.png" },
  { id: 199, name: "سلوفينيا", flag: "https://flagcdn.com/w40/si.png" },
  { id: 200, name: "جزر سليمان", flag: "https://flagcdn.com/w40/sb.png" },

  { id: 201, name: "الصومال", flag: "https://flagcdn.com/w40/so.png" },
  { id: 202, name: "جنوب أفريقيا", flag: "https://flagcdn.com/w40/za.png" },
  { id: 203, name: "جورجيا الجنوبية وجزر ساندويتش الجنوبية", flag: "https://flagcdn.com/w40/gs.png" },
  { id: 204, name: "كوريا الجنوبية", flag: "https://flagcdn.com/w40/kr.png" },
  { id: 205, name: "جنوب السودان", flag: "https://flagcdn.com/w40/ss.png" },
  { id: 206, name: "إسبانيا", flag: "https://flagcdn.com/w40/es.png" },
  { id: 207, name: "سريلانكا", flag: "https://flagcdn.com/w40/lk.png" },
  { id: 208, name: "السودان", flag: "https://flagcdn.com/w40/sd.png" },
  { id: 209, name: "سورينام", flag: "https://flagcdn.com/w40/sr.png" },
  { id: 210, name: "سفالبارد ويان ماين", flag: "https://flagcdn.com/w40/sj.png" },

  { id: 211, name: "السويد", flag: "https://flagcdn.com/w40/se.png" },
  { id: 212, name: "سويسرا", flag: "https://flagcdn.com/w40/ch.png" },
  { id: 213, name: "سوريا", flag: "https://flagcdn.com/w40/sy.png" },
  { id: 214, name: "تايوان", flag: "https://flagcdn.com/w40/tw.png" },
  { id: 215, name: "طاجيكستان", flag: "https://flagcdn.com/w40/tj.png" },
  { id: 216, name: "تنزانيا", flag: "https://flagcdn.com/w40/tz.png" },
  { id: 217, name: "تايلاند", flag: "https://flagcdn.com/w40/th.png" },
  { id: 218, name: "تيمور الشرقية", flag: "https://flagcdn.com/w40/tl.png" },
  { id: 219, name: "توغو", flag: "https://flagcdn.com/w40/tg.png" },
  { id: 220, name: "توكيلاو", flag: "https://flagcdn.com/w40/tk.png" },

  { id: 221, name: "تونغا", flag: "https://flagcdn.com/w40/to.png" },
  { id: 222, name: "ترينيداد وتوباغو", flag: "https://flagcdn.com/w40/tt.png" },
  { id: 223, name: "تونس", flag: "https://flagcdn.com/w40/tn.png" },
  { id: 224, name: "تركيا", flag: "https://flagcdn.com/w40/tr.png" },
  { id: 225, name: "تركمانستان", flag: "https://flagcdn.com/w40/tm.png" },
  { id: 226, name: "توفالو", flag: "https://flagcdn.com/w40/tv.png" },
  { id: 227, name: "أوغندا", flag: "https://flagcdn.com/w40/ug.png" },
  { id: 228, name: "أوكرانيا", flag: "https://flagcdn.com/w40/ua.png" },
  { id: 229, name: "الإمارات العربية المتحدة", flag: "https://flagcdn.com/w40/ae.png" },
  { id: 230, name: "المملكة المتحدة", flag: "https://flagcdn.com/w40/gb.png" },

  { id: 231, name: "الولايات المتحدة الأمريكية", flag: "https://flagcdn.com/w40/us.png" },
  { id: 232, name: "أوروغواي", flag: "https://flagcdn.com/w40/uy.png" },
  { id: 233, name: "أوزبكستان", flag: "https://flagcdn.com/w40/uz.png" },
  { id: 234, name: "فانواتو", flag: "https://flagcdn.com/w40/vu.png" },
  { id: 235, name: "فنزويلا", flag: "https://flagcdn.com/w40/ve.png" },
  { id: 236, name: "فيتنام", flag: "https://flagcdn.com/w40/vn.png" },
  { id: 237, name: "جزر العذراء البريطانية", flag: "https://flagcdn.com/w40/vg.png" },
  { id: 238, name: "جزر العذراء الأمريكية", flag: "https://flagcdn.com/w40/vi.png" },
  { id: 239, name: "واليس وفوتونا", flag: "https://flagcdn.com/w40/wf.png" },
  { id: 240, name: "الصحراء الغربية", flag: "https://flagcdn.com/w40/eh.png" },

  { id: 241, name: "اليمن", flag: "https://flagcdn.com/w40/ye.png" },
  { id: 242, name: "زامبيا", flag: "https://flagcdn.com/w40/zm.png" },
  { id: 243, name: "زيمبابوي", flag: "https://flagcdn.com/w40/zw.png" },
  { id: 244, name: "كوسوفو", flag: "https://flagcdn.com/w40/xk.png" },
  { id: 245, name: "صوماليلاند", flag: "https://flagcdn.com/w40/so.png" },
  { id: 246, name: "تايوان (جمهورية الصين)", flag: "https://flagcdn.com/w40/tw.png" },
  { id: 247, name: "فلسطين", flag: "https://flagcdn.com/w40/ps.png" },
  { id: 248, name: "أوسيتيا الجنوبية", flag: "https://flagcdn.com/w40/rs.png" },
  { id: 249, name: "أبخازيا", flag: "https://flagcdn.com/w40/ge.png" },]
//France content
const french = {
  edit: "Modifier",
   myJobs: "Mes emplois",
    createJob: "Créer un emploi",
    proposals: "Propositions",
    create: "Créer",
  alreadySignedInMessage:"Vous êtes déjà connecté.",
    organizationName: "Nom de l’organisation",
  donhave: "Vous n’avez pas de compte ?",
  createOne: "Créez-en un",
  notMemeber:"Pas encore membre ?",
  password: "Mot de passe",
  signUp: "S’inscrire",
  fname: "Prénom",
  lname: "Nom de famille",
  email: "Adresse e-mail",
  role: "Rôle",
  employee: "Employé",
  employer: "Employeur",
  haveAccount: "Vous avez déjà un compte ?",
  logIn: "Se connecter",
  apply:"Postuler",
  home_link: "Accueil",
  sent_link: "Candidatures",
  saved_link: "Favoris",
  explore_link: "Découvrir",
  dashboard_link: "Tableau de bord",
  find_job: "Trouver un emploi",
  french:"Appliquer",
  hero_header: "Entrez dans votre avenir avec l’emploi idéal",
  hero_paragraph:
    "Parcourez des milliers d’offres, postulez en quelques secondes et décrochez le poste que vous méritez.",

  job_posted: "Offres publiées",
  active_users: "Demandeurs d’emploi actifs",
  campany_amount: "Entreprises qui recrutent",

  motive_header: "La meilleure façon de trouver un emploi",
  motive_paragraph:
    "Transformez chaque candidature en véritable opportunité grâce à des conseils d’experts en réseautage, en personal branding et en maîtrise des entretiens.",

  about_us: "À propos de nous",
  about_paragraph:
    "Jobify est une organisation neutre et autonome qui met en relation les employeurs et les demandeurs d’emploi dans le monde entier. Fondée en 2026 par Bereket Girma, Jobify est présente dans plus de 80 pays et simplifie le recrutement et la recherche d’emploi grâce à une plateforme fiable et conviviale.",

  staf_header: "Notre communauté",

  footer_paragraph:
    "Jobify connecte les demandeurs d’emploi aux meilleures opportunités à travers le monde. Postulez en quelques secondes et décrochez le poste de vos rêves.",

  quick_link: "Liens rapides",
  about: "À propos",

  footer_about_paragraph: `Fondée en 2026 par Bereket Girma, Jobify est présente dans plus de 80 pays,
            et simplifie le recrutement et la recherche d’emploi.`,

  learn_more: "En savoir plus",
  contact: "Contact",
  phone: "Téléphone",
  right: " Tous droits réservés.",
  links: "Liens rapides",
  categories: "Catégories",
  location: "Lieu",
  jobType: "Type de poste",
  salary: "Salaire",

  jobSearchPlaceholder: "Rechercher un emploi",
  proposalPlaceholder: "Saisissez les détails de la proposition...",
  writeProposal: "Rédiger une proposition",
  markdownSupport: "Formatage Markdown pris en charge",

  headline: "Trouvez l’emploi idéal",
  careers: "Carrières",
  below: "Ci-dessous",
  send: "Envoyer",

  dashboard: "Tableau de bord",
  workspace: "Espace de travail",
  inbox: "Boîte de réception",

  name: "Nom",
  post: "Publier",
  team: "Notre équipe",

  aboutJob: "À propos du poste",
  signOut: "Se déconnecter",
  jobDetails: "Détails du poste",
  title: "Titre",
  language: "Langue",
};
const teamsFr = [
  {
    name: "Oliver Benjamin",
    img: "/photo-1560250097-0b93528c311a.avif",
    description:
      "Pilotage de la stratégie et de la vision pour développer les plateformes de recrutement basées sur l’IA",
    stars: 4.5,
    halfStar: true,
    color: "bg-sky-600",
    title: "PDG",
  },
  {
    name: "Emily Grace",
    img: "/photo-1494790108377-be9c29b29330.avif",
    description:
      "Gestion des équipes et des livraisons afin de garantir des opérations fiables",
    stars: 5,
    halfStar: false,
    color: "bg-pink-500",
    title: "Cheffe d’équipe",
  },
  {
    name: "Alexander Carter",
    img: "/photo-1599566150163-29194dcaad36.avif",
    description:
      "Supervision de la planification financière, de la conformité et de la croissance à long terme",
    stars: 5,
    halfStar: false,
    color: "bg-green-500",
    title: "Directeur financier",
  },
  {
    name: "Thomas Anderson",
    img: "/premium_photo-1689539137236-b68e436248de.avif",
    description:
      "Soutien aux tâches quotidiennes, coordination et fluidité des opérations principales",
    stars: 3,
    halfStar: true,
    color: "bg-yellow-500",
    title: "Assistant",
  },
];
const categoriesFr = [
  { id: 1, name: "Santé et Médical" },
  { id: 2, name: "Technologies de l’Information (TI) et Logiciels" },
  { id: 3, name: "Éducation et Enseignement" },
  { id: 4, name: "Ingénierie et Technique" },
  { id: 5, name: "Finance et Comptabilité" },
  { id: 6, name: "Ventes et Marketing" },
  { id: 7, name: "Ressources Humaines et Administration" },
  { id: 8, name: "Création et Design" },
  { id: 9, name: "Hôtellerie et Tourisme" },
  { id: 10, name: "Fabrication et Métiers" },
];
const jobTypesFr = [
  { id: 1, name: "Temps plein" },
  { id: 2, name: "Temps partiel" },
  { id: 3, name: "Contrat" },
  { id: 4, name: "Temporaire" },
  { id: 5, name: "Stage" },
  { id: 6, name: "Indépendant / Freelance" },
  { id: 7, name: "Télétravail" },
  { id: 8, name: "Hybride" },
  { id: 9, name: "Sur site" },
  { id: 10, name: "Saisonnier" },
  { id: 11, name: "Bénévole" },
  { id: 12, name: "Apprentissage" },
];
const countriesFr: countriesType[] = [
  { id: 1, name: "Afghanistan", flag: "https://flagcdn.com/w40/af.png" },
  { id: 2, name: "Îles Åland", flag: "https://flagcdn.com/w40/ax.png" },
  { id: 3, name: "Albanie", flag: "https://flagcdn.com/w40/al.png" },
  { id: 4, name: "Algérie", flag: "https://flagcdn.com/w40/dz.png" },
  { id: 5, name: "Samoa américaines", flag: "https://flagcdn.com/w40/as.png" },
  { id: 6, name: "Andorre", flag: "https://flagcdn.com/w40/ad.png" },
  { id: 7, name: "Angola", flag: "https://flagcdn.com/w40/ao.png" },
  { id: 8, name: "Anguilla", flag: "https://flagcdn.com/w40/ai.png" },
  { id: 9, name: "Antarctique", flag: "https://flagcdn.com/w40/aq.png" },
  { id: 10, name: "Antigua-et-Barbuda", flag: "https://flagcdn.com/w40/ag.png" },

  { id: 11, name: "Argentine", flag: "https://flagcdn.com/w40/ar.png" },
  { id: 12, name: "Arménie", flag: "https://flagcdn.com/w40/am.png" },
  { id: 13, name: "Aruba", flag: "https://flagcdn.com/w40/aw.png" },
  { id: 14, name: "Australie", flag: "https://flagcdn.com/w40/au.png" },
  { id: 15, name: "Autriche", flag: "https://flagcdn.com/w40/at.png" },
  { id: 16, name: "Azerbaïdjan", flag: "https://flagcdn.com/w40/az.png" },
  { id: 17, name: "Bahamas", flag: "https://flagcdn.com/w40/bs.png" },
  { id: 18, name: "Bahreïn", flag: "https://flagcdn.com/w40/bh.png" },
  { id: 19, name: "Bangladesh", flag: "https://flagcdn.com/w40/bd.png" },
  { id: 20, name: "Barbade", flag: "https://flagcdn.com/w40/bb.png" },

  { id: 21, name: "Biélorussie", flag: "https://flagcdn.com/w40/by.png" },
  { id: 22, name: "Belgique", flag: "https://flagcdn.com/w40/be.png" },
  { id: 23, name: "Belize", flag: "https://flagcdn.com/w40/bz.png" },
  { id: 24, name: "Bénin", flag: "https://flagcdn.com/w40/bj.png" },
  { id: 25, name: "Bermudes", flag: "https://flagcdn.com/w40/bm.png" },
  { id: 26, name: "Bhoutan", flag: "https://flagcdn.com/w40/bt.png" },
  { id: 27, name: "Bolivie", flag: "https://flagcdn.com/w40/bo.png" },
  { id: 28, name: "Bonaire, Saint-Eustache et Saba", flag: "https://flagcdn.com/w40/bq.png" },
  { id: 29, name: "Bosnie-Herzégovine", flag: "https://flagcdn.com/w40/ba.png" },
  { id: 30, name: "Botswana", flag: "https://flagcdn.com/w40/bw.png" },

  { id: 31, name: "Île Bouvet", flag: "https://flagcdn.com/w40/bv.png" },
  { id: 32, name: "Brésil", flag: "https://flagcdn.com/w40/br.png" },
  { id: 33, name: "Territoire britannique de l’océan Indien", flag: "https://flagcdn.com/w40/io.png" },
  { id: 34, name: "Brunéi", flag: "https://flagcdn.com/w40/bn.png" },
  { id: 35, name: "Bulgarie", flag: "https://flagcdn.com/w40/bg.png" },
  { id: 36, name: "Burkina Faso", flag: "https://flagcdn.com/w40/bf.png" },
  { id: 37, name: "Burundi", flag: "https://flagcdn.com/w40/bi.png" },
  { id: 38, name: "Cap-Vert", flag: "https://flagcdn.com/w40/cv.png" },
  { id: 39, name: "Cambodge", flag: "https://flagcdn.com/w40/kh.png" },
  { id: 40, name: "Cameroun", flag: "https://flagcdn.com/w40/cm.png" },

  { id: 41, name: "Canada", flag: "https://flagcdn.com/w40/ca.png" },
  { id: 42, name: "Îles Caïmans", flag: "https://flagcdn.com/w40/ky.png" },
  { id: 43, name: "République centrafricaine", flag: "https://flagcdn.com/w40/cf.png" },
  { id: 44, name: "Tchad", flag: "https://flagcdn.com/w40/td.png" },
  { id: 45, name: "Chili", flag: "https://flagcdn.com/w40/cl.png" },
  { id: 46, name: "Chine", flag: "https://flagcdn.com/w40/cn.png" },
  { id: 47, name: "Île Christmas", flag: "https://flagcdn.com/w40/cx.png" },
  { id: 48, name: "Îles Cocos (Keeling)", flag: "https://flagcdn.com/w40/cc.png" },
  { id: 49, name: "Colombie", flag: "https://flagcdn.com/w40/co.png" },
  { id: 50, name: "Comores", flag: "https://flagcdn.com/w40/km.png" },

  { id: 51, name: "République démocratique du Congo", flag: "https://flagcdn.com/w40/cd.png" },
  { id: 52, name: "République du Congo", flag: "https://flagcdn.com/w40/cg.png" },
  { id: 53, name: "Îles Cook", flag: "https://flagcdn.com/w40/ck.png" },
  { id: 54, name: "Costa Rica", flag: "https://flagcdn.com/w40/cr.png" },
  { id: 55, name: "Côte d’Ivoire", flag: "https://flagcdn.com/w40/ci.png" },
  { id: 56, name: "Croatie", flag: "https://flagcdn.com/w40/hr.png" },
  { id: 57, name: "Cuba", flag: "https://flagcdn.com/w40/cu.png" },
  { id: 58, name: "Curaçao", flag: "https://flagcdn.com/w40/cw.png" },
  { id: 59, name: "Chypre", flag: "https://flagcdn.com/w40/cy.png" },
  { id: 60, name: "République tchèque", flag: "https://flagcdn.com/w40/cz.png" },
  { id: 61, name: "Danemark", flag: "https://flagcdn.com/w40/dk.png" },
  { id: 62, name: "Djibouti", flag: "https://flagcdn.com/w40/dj.png" },
  { id: 63, name: "Dominique", flag: "https://flagcdn.com/w40/dm.png" },
  { id: 64, name: "République dominicaine", flag: "https://flagcdn.com/w40/do.png" },
  { id: 65, name: "Équateur", flag: "https://flagcdn.com/w40/ec.png" },
  { id: 66, name: "Égypte", flag: "https://flagcdn.com/w40/eg.png" },
  { id: 67, name: "Salvador", flag: "https://flagcdn.com/w40/sv.png" },
  { id: 68, name: "Guinée équatoriale", flag: "https://flagcdn.com/w40/gq.png" },
  { id: 69, name: "Érythrée", flag: "https://flagcdn.com/w40/er.png" },
  { id: 70, name: "Estonie", flag: "https://flagcdn.com/w40/ee.png" },

  { id: 71, name: "Eswatini", flag: "https://flagcdn.com/w40/sz.png" },
  { id: 72, name: "Éthiopie", flag: "https://flagcdn.com/w40/et.png" },
  { id: 73, name: "Îles Falkland", flag: "https://flagcdn.com/w40/fk.png" },
  { id: 74, name: "Îles Féroé", flag: "https://flagcdn.com/w40/fo.png" },
  { id: 75, name: "Fidji", flag: "https://flagcdn.com/w40/fj.png" },
  { id: 76, name: "Finlande", flag: "https://flagcdn.com/w40/fi.png" },
  { id: 77, name: "France", flag: "https://flagcdn.com/w40/fr.png" },
  { id: 78, name: "Guyane française", flag: "https://flagcdn.com/w40/gf.png" },
  { id: 79, name: "Polynésie française", flag: "https://flagcdn.com/w40/pf.png" },
  { id: 80, name: "Terres australes françaises", flag: "https://flagcdn.com/w40/tf.png" },

  { id: 81, name: "Gabon", flag: "https://flagcdn.com/w40/ga.png" },
  { id: 82, name: "Gambie", flag: "https://flagcdn.com/w40/gm.png" },
  { id: 83, name: "Géorgie", flag: "https://flagcdn.com/w40/ge.png" },
  { id: 84, name: "Allemagne", flag: "https://flagcdn.com/w40/de.png" },
  { id: 85, name: "Ghana", flag: "https://flagcdn.com/w40/gh.png" },
  { id: 86, name: "Gibraltar", flag: "https://flagcdn.com/w40/gi.png" },
  { id: 87, name: "Grèce", flag: "https://flagcdn.com/w40/gr.png" },
  { id: 88, name: "Groenland", flag: "https://flagcdn.com/w40/gl.png" },
  { id: 89, name: "Grenade", flag: "https://flagcdn.com/w40/gd.png" },
  { id: 90, name: "Guadeloupe", flag: "https://flagcdn.com/w40/gp.png" },

  { id: 91, name: "Guam", flag: "https://flagcdn.com/w40/gu.png" },
  { id: 92, name: "Guatemala", flag: "https://flagcdn.com/w40/gt.png" },
  { id: 93, name: "Guernesey", flag: "https://flagcdn.com/w40/gg.png" },
  { id: 94, name: "Guinée", flag: "https://flagcdn.com/w40/gn.png" },
  { id: 95, name: "Guinée-Bissau", flag: "https://flagcdn.com/w40/gw.png" },
  { id: 96, name: "Guyana", flag: "https://flagcdn.com/w40/gy.png" },
  { id: 97, name: "Haïti", flag: "https://flagcdn.com/w40/ht.png" },
  { id: 98, name: "Île Heard et îles McDonald", flag: "https://flagcdn.com/w40/hm.png" },
  { id: 99, name: "Saint-Siège", flag: "https://flagcdn.com/w40/va.png" },
  { id: 100, name: "Honduras", flag: "https://flagcdn.com/w40/hn.png" },

  { id: 101, name: "Hong Kong", flag: "https://flagcdn.com/w40/hk.png" },
  { id: 102, name: "Hongrie", flag: "https://flagcdn.com/w40/hu.png" },
  { id: 103, name: "Islande", flag: "https://flagcdn.com/w40/is.png" },
  { id: 104, name: "Inde", flag: "https://flagcdn.com/w40/in.png" },
  { id: 105, name: "Indonésie", flag: "https://flagcdn.com/w40/id.png" },
  { id: 106, name: "Iran", flag: "https://flagcdn.com/w40/ir.png" },
  { id: 107, name: "Irak", flag: "https://flagcdn.com/w40/iq.png" },
  { id: 108, name: "Irlande", flag: "https://flagcdn.com/w40/ie.png" },
  { id: 109, name: "Île de Man", flag: "https://flagcdn.com/w40/im.png" },
  { id: 110, name: "Israël", flag: "https://flagcdn.com/w40/il.png" },

  { id: 111, name: "Italie", flag: "https://flagcdn.com/w40/it.png" },
  { id: 112, name: "Jamaïque", flag: "https://flagcdn.com/w40/jm.png" },
  { id: 113, name: "Japon", flag: "https://flagcdn.com/w40/jp.png" },
  { id: 114, name: "Jersey", flag: "https://flagcdn.com/w40/je.png" },
  { id: 115, name: "Jordanie", flag: "https://flagcdn.com/w40/jo.png" },
  { id: 116, name: "Kazakhstan", flag: "https://flagcdn.com/w40/kz.png" },
  { id: 117, name: "Kenya", flag: "https://flagcdn.com/w40/ke.png" },
  { id: 118, name: "Kiribati", flag: "https://flagcdn.com/w40/ki.png" },
  { id: 119, name: "Koweït", flag: "https://flagcdn.com/w40/kw.png" },
  { id: 120, name: "Kirghizistan", flag: "https://flagcdn.com/w40/kg.png" },

  { id: 121, name: "Laos", flag: "https://flagcdn.com/w40/la.png" },
  { id: 122, name: "Lettonie", flag: "https://flagcdn.com/w40/lv.png" },
  { id: 123, name: "Liban", flag: "https://flagcdn.com/w40/lb.png" },
  { id: 124, name: "Lesotho", flag: "https://flagcdn.com/w40/ls.png" },
  { id: 125, name: "Libéria", flag: "https://flagcdn.com/w40/lr.png" },
  { id: 126, name: "Libye", flag: "https://flagcdn.com/w40/ly.png" },
  { id: 127, name: "Liechtenstein", flag: "https://flagcdn.com/w40/li.png" },
  { id: 128, name: "Lituanie", flag: "https://flagcdn.com/w40/lt.png" },
  { id: 129, name: "Luxembourg", flag: "https://flagcdn.com/w40/lu.png" },
  { id: 130, name: "Macao", flag: "https://flagcdn.com/w40/mo.png" },

  { id: 131, name: "Madagascar", flag: "https://flagcdn.com/w40/mg.png" },
  { id: 132, name: "Malawi", flag: "https://flagcdn.com/w40/mw.png" },
  { id: 133, name: "Malaisie", flag: "https://flagcdn.com/w40/my.png" },
  { id: 134, name: "Maldives", flag: "https://flagcdn.com/w40/mv.png" },
  { id: 135, name: "Mali", flag: "https://flagcdn.com/w40/ml.png" },
  { id: 136, name: "Malte", flag: "https://flagcdn.com/w40/mt.png" },
  { id: 137, name: "Îles Marshall", flag: "https://flagcdn.com/w40/mh.png" },
  { id: 138, name: "Martinique", flag: "https://flagcdn.com/w40/mq.png" },
  { id: 139, name: "Mauritanie", flag: "https://flagcdn.com/w40/mr.png" },
  { id: 140, name: "Maurice", flag: "https://flagcdn.com/w40/mu.png" },

  { id: 141, name: "Mayotte", flag: "https://flagcdn.com/w40/yt.png" },
  { id: 142, name: "Mexique", flag: "https://flagcdn.com/w40/mx.png" },
  { id: 143, name: "Micronésie", flag: "https://flagcdn.com/w40/fm.png" },
  { id: 144, name: "Moldavie", flag: "https://flagcdn.com/w40/md.png" },
  { id: 145, name: "Monaco", flag: "https://flagcdn.com/w40/mc.png" },
  { id: 146, name: "Mongolie", flag: "https://flagcdn.com/w40/mn.png" },
  { id: 147, name: "Monténégro", flag: "https://flagcdn.com/w40/me.png" },
  { id: 148, name: "Montserrat", flag: "https://flagcdn.com/w40/ms.png" },
  { id: 149, name: "Maroc", flag: "https://flagcdn.com/w40/ma.png" },
  { id: 150, name: "Mozambique", flag: "https://flagcdn.com/w40/mz.png" },

  { id: 151, name: "Myanmar", flag: "https://flagcdn.com/w40/mm.png" },
  { id: 152, name: "Namibie", flag: "https://flagcdn.com/w40/na.png" },
  { id: 153, name: "Nauru", flag: "https://flagcdn.com/w40/nr.png" },
  { id: 154, name: "Népal", flag: "https://flagcdn.com/w40/np.png" },
  { id: 155, name: "Pays-Bas", flag: "https://flagcdn.com/w40/nl.png" },
  { id: 156, name: "Nouvelle-Calédonie", flag: "https://flagcdn.com/w40/nc.png" },
  { id: 157, name: "Nouvelle-Zélande", flag: "https://flagcdn.com/w40/nz.png" },
  { id: 158, name: "Nicaragua", flag: "https://flagcdn.com/w40/ni.png" },
  { id: 159, name: "Niger", flag: "https://flagcdn.com/w40/ne.png" },
  { id: 160, name: "Nigeria", flag: "https://flagcdn.com/w40/ng.png" },
  { id: 161, name: "Macédoine du Nord", flag: "https://flagcdn.com/w40/mk.png" },
  { id: 162, name: "Norvège", flag: "https://flagcdn.com/w40/no.png" },
  { id: 163, name: "Oman", flag: "https://flagcdn.com/w40/om.png" },
  { id: 164, name: "Pakistan", flag: "https://flagcdn.com/w40/pk.png" },
  { id: 165, name: "Palaos", flag: "https://flagcdn.com/w40/pw.png" },
  { id: 166, name: "Palestine", flag: "https://flagcdn.com/w40/ps.png" },
  { id: 167, name: "Panama", flag: "https://flagcdn.com/w40/pa.png" },
  { id: 168, name: "Papouasie-Nouvelle-Guinée", flag: "https://flagcdn.com/w40/pg.png" },
  { id: 169, name: "Paraguay", flag: "https://flagcdn.com/w40/py.png" },
  { id: 170, name: "Pérou", flag: "https://flagcdn.com/w40/pe.png" },

  { id: 171, name: "Philippines", flag: "https://flagcdn.com/w40/ph.png" },
  { id: 172, name: "Îles Pitcairn", flag: "https://flagcdn.com/w40/pn.png" },
  { id: 173, name: "Pologne", flag: "https://flagcdn.com/w40/pl.png" },
  { id: 174, name: "Portugal", flag: "https://flagcdn.com/w40/pt.png" },
  { id: 175, name: "Porto Rico", flag: "https://flagcdn.com/w40/pr.png" },
  { id: 176, name: "Qatar", flag: "https://flagcdn.com/w40/qa.png" },
  { id: 177, name: "Réunion", flag: "https://flagcdn.com/w40/re.png" },
  { id: 178, name: "Roumanie", flag: "https://flagcdn.com/w40/ro.png" },
  { id: 179, name: "Russie", flag: "https://flagcdn.com/w40/ru.png" },
  { id: 180, name: "Rwanda", flag: "https://flagcdn.com/w40/rw.png" },

  { id: 181, name: "Saint-Barthélemy", flag: "https://flagcdn.com/w40/bl.png" },
  { id: 182, name: "Sainte-Hélène, Ascension et Tristan da Cunha", flag: "https://flagcdn.com/w40/sh.png" },
  { id: 183, name: "Saint-Christophe-et-Niévès", flag: "https://flagcdn.com/w40/kn.png" },
  { id: 184, name: "Sainte-Lucie", flag: "https://flagcdn.com/w40/lc.png" },
  { id: 185, name: "Saint-Martin", flag: "https://flagcdn.com/w40/mf.png" },
  { id: 186, name: "Saint-Pierre-et-Miquelon", flag: "https://flagcdn.com/w40/pm.png" },
  { id: 187, name: "Saint-Vincent-et-les-Grenadines", flag: "https://flagcdn.com/w40/vc.png" },
  { id: 188, name: "Samoa", flag: "https://flagcdn.com/w40/ws.png" },
  { id: 189, name: "Saint-Marin", flag: "https://flagcdn.com/w40/sm.png" },
  { id: 190, name: "Sao Tomé-et-Principe", flag: "https://flagcdn.com/w40/st.png" },

  { id: 191, name: "Arabie saoudite", flag: "https://flagcdn.com/w40/sa.png" },
  { id: 192, name: "Sénégal", flag: "https://flagcdn.com/w40/sn.png" },
  { id: 193, name: "Serbie", flag: "https://flagcdn.com/w40/rs.png" },
  { id: 194, name: "Seychelles", flag: "https://flagcdn.com/w40/sc.png" },
  { id: 195, name: "Sierra Leone", flag: "https://flagcdn.com/w40/sl.png" },
  { id: 196, name: "Singapour", flag: "https://flagcdn.com/w40/sg.png" },
  { id: 197, name: "Saint-Martin néerlandais", flag: "https://flagcdn.com/w40/sx.png" },
  { id: 198, name: "Slovaquie", flag: "https://flagcdn.com/w40/sk.png" },
  { id: 199, name: "Slovénie", flag: "https://flagcdn.com/w40/si.png" },
  { id: 200, name: "Îles Salomon", flag: "https://flagcdn.com/w40/sb.png" },

  { id: 201, name: "Somalie", flag: "https://flagcdn.com/w40/so.png" },
  { id: 202, name: "Afrique du Sud", flag: "https://flagcdn.com/w40/za.png" },
  { id: 203, name: "Géorgie du Sud et îles Sandwich du Sud", flag: "https://flagcdn.com/w40/gs.png" },
  { id: 204, name: "Corée du Sud", flag: "https://flagcdn.com/w40/kr.png" },
  { id: 205, name: "Soudan du Sud", flag: "https://flagcdn.com/w40/ss.png" },
  { id: 206, name: "Espagne", flag: "https://flagcdn.com/w40/es.png" },
  { id: 207, name: "Sri Lanka", flag: "https://flagcdn.com/w40/lk.png" },
  { id: 208, name: "Soudan", flag: "https://flagcdn.com/w40/sd.png" },
  { id: 209, name: "Suriname", flag: "https://flagcdn.com/w40/sr.png" },
  { id: 210, name: "Svalbard et Jan Mayen", flag: "https://flagcdn.com/w40/sj.png" },

  { id: 211, name: "Suède", flag: "https://flagcdn.com/w40/se.png" },
  { id: 212, name: "Suisse", flag: "https://flagcdn.com/w40/ch.png" },
  { id: 213, name: "Syrie", flag: "https://flagcdn.com/w40/sy.png" },
  { id: 214, name: "Taïwan", flag: "https://flagcdn.com/w40/tw.png" },
  { id: 215, name: "Tadjikistan", flag: "https://flagcdn.com/w40/tj.png" },
  { id: 216, name: "Tanzanie", flag: "https://flagcdn.com/w40/tz.png" },
  { id: 217, name: "Thaïlande", flag: "https://flagcdn.com/w40/th.png" },
  { id: 218, name: "Timor oriental", flag: "https://flagcdn.com/w40/tl.png" },
  { id: 219, name: "Togo", flag: "https://flagcdn.com/w40/tg.png" },
  { id: 220, name: "Tokelau", flag: "https://flagcdn.com/w40/tk.png" },

  { id: 221, name: "Tonga", flag: "https://flagcdn.com/w40/to.png" },
  { id: 222, name: "Trinité-et-Tobago", flag: "https://flagcdn.com/w40/tt.png" },
  { id: 223, name: "Tunisie", flag: "https://flagcdn.com/w40/tn.png" },
  { id: 224, name: "Turquie", flag: "https://flagcdn.com/w40/tr.png" },
  { id: 225, name: "Turkménistan", flag: "https://flagcdn.com/w40/tm.png" },
  { id: 226, name: "Tuvalu", flag: "https://flagcdn.com/w40/tv.png" },
  { id: 227, name: "Ouganda", flag: "https://flagcdn.com/w40/ug.png" },
  { id: 228, name: "Ukraine", flag: "https://flagcdn.com/w40/ua.png" },
  { id: 229, name: "Émirats arabes unis", flag: "https://flagcdn.com/w40/ae.png" },
  { id: 230, name: "Royaume-Uni", flag: "https://flagcdn.com/w40/gb.png" },

  { id: 231, name: "États-Unis", flag: "https://flagcdn.com/w40/us.png" },
  { id: 232, name: "Uruguay", flag: "https://flagcdn.com/w40/uy.png" },
  { id: 233, name: "Ouzbékistan", flag: "https://flagcdn.com/w40/uz.png" },
  { id: 234, name: "Vanuatu", flag: "https://flagcdn.com/w40/vu.png" },
  { id: 235, name: "Venezuela", flag: "https://flagcdn.com/w40/ve.png" },
  { id: 236, name: "Viêt Nam", flag: "https://flagcdn.com/w40/vn.png" },
  { id: 237, name: "Îles Vierges britanniques", flag: "https://flagcdn.com/w40/vg.png" },
  { id: 238, name: "Îles Vierges des États-Unis", flag: "https://flagcdn.com/w40/vi.png" },
  { id: 239, name: "Wallis-et-Futuna", flag: "https://flagcdn.com/w40/wf.png" },
  { id: 240, name: "Sahara occidental", flag: "https://flagcdn.com/w40/eh.png" },

  { id: 241, name: "Yémen", flag: "https://flagcdn.com/w40/ye.png" },
  { id: 242, name: "Zambie", flag: "https://flagcdn.com/w40/zm.png" },
  { id: 243, name: "Zimbabwe", flag: "https://flagcdn.com/w40/zw.png" },
  { id: 244, name: "Kosovo", flag: "https://flagcdn.com/w40/xk.png" },
  { id: 245, name: "Somaliland", flag: "https://flagcdn.com/w40/so.png" },
  { id: 246, name: "Taïwan (République de Chine)", flag: "https://flagcdn.com/w40/tw.png" },
  { id: 247, name: "Palestine", flag: "https://flagcdn.com/w40/ps.png" },
  { id: 248, name: "Ossétie du Sud", flag: "https://flagcdn.com/w40/rs.png" },
  { id: 249, name: "Abkhazie", flag: "https://flagcdn.com/w40/ge.png" },
];
//Amharic content
const amharic = {
  edit: "አርትዕ",
  myJobs: "ስራዬ",
    createJob: "ስራ ፍጠር",
    proposals: "ጥያቄዎች",
    create: "ፍጠር",
  alreadySignedInMessage:"አንተ ከዚህ ቀደም ተገብተሃል።",
  organizationName: "የድርጅት ስም",
  donhave: "አካውንት የለዎትም?",
  createOne: "አንድ ይፍጠሩ",
  notMemeber:"አባል አይደሉም?",
  password: "የይለፍ ቃል",
  signUp: "ይመዝገቡ",
  fname: "የመጀመሪያ ስም",
  lname: "የአባት ስም",
  email: "ኢሜይል",
  role: "ሚና",
  employee: "ሰራተኛ",
  employer: "ቀጣሪ",
  haveAccount: "አካውንት አለዎት?",
  logIn: "ግባ",
  home_link: "መነሻ",
  sent_link: "ማመልከቻዎች",
  saved_link: "የተቀመጡ",
  explore_link: "ያስሱ",
  dashboard_link: "ዳሽቦርድ",
  find_job: "ስራ ፈልግ",
  apply:"ማመልከት",
  hero_header: "ከተስፋዎ ጋር ወደፊትዎን ይጀምሩ",
  hero_paragraph:
    "ሺዎች የሆኑ የስራ ማስታወቂያዎችን ይመልከቱ፣ በጥቂት ሰከንዶች ያመልክቱ እና የሚገባዎትን ስራ ያግኙ።",

  job_posted: "የተለጠፉ ስራዎች",
  active_users: "ንቁ የስራ ፈላጊዎች",
  campany_amount: "ቀጣሪ ድርጅቶች",

  motive_header: "ስራ ለማግኘት የተሻለ መንገድ",
  motive_paragraph:
    "በኔትወርኪንግ፣ በግል ብራንዲንግ እና በቃለ-መጠይቅ ብቃት ላይ የሚሰጡ የባለሙያ መመሪያዎችን በመጠቀም እያንዳንዱን የስራ ማመልከቻ ወደ እውነተኛ ዕድል ይቀይሩ።",

  about_us: "ስለ እኛ",
  about_paragraph:
    "Jobify ቀጣሪዎችን እና የስራ ፈላጊዎችን በዓለም አቀፍ ደረጃ የሚያገናኝ ገለልተኛና ነፃ ድርጅት ነው። በ2026 በBereket Girma የተመሰረተው Jobify በ80 በላይ አገሮች ውስጥ ይሰራል፣ እና የስራ ፈለግን እና ቀጣሪነትን በታማኝና ቀላል መድረክ ያቀላጥፋል።",

  staf_header: "ማህበረሰባችን",

  footer_paragraph:
    "Jobify የስራ ፈላጊዎችን ከምርጥ ዕድሎች ጋር በዓለም አቀፍ ደረጃ ያገናኛል። በጥቂት ሰከንዶች ያመልክቱ እና የሕልምዎን ስራ ያግኙ።",

  quick_link: "ፈጣን አገናኞች",
  about: "ስለ",

  footer_about_paragraph: `Jobify በ2026 በBereket Girma የተመሰረተ ሲሆን፣
            በ80 በላይ አገሮች ውስጥ ይሰራል እና የስራ ፈለግን እና ቀጣሪነትን ያቀላጥፋል።`,

  learn_more: "ተጨማሪ ይወቁ",
  contact: "ያግኙን",
  phone: "ስልክ",
  right: " መብቶቹ ሁሉ የተጠበቁ ናቸው።",
  links: "ፈጣን አገናኞች",
  categories: "ምድቦች",
  location: "አካባቢ",
  jobType: "የሥራ አይነት",
  salary: "ደመወዝ",

  jobSearchPlaceholder: "ሥራ ፈልግ",
  proposalPlaceholder: "የፕሮፖዛል ዝርዝሮችን ያስገቡ...",
  writeProposal: "ፕሮፖዛል ጻፍ",
  markdownSupport: "የMarkdown ፎርማት ይደገፋል",

  headline: "ተስማሚ ሥራዎን ያግኙ",
  careers: "ሙያዎች",
  below: "ከዚህ በታች",
  send: "ላክ",

  dashboard: "ዳሽቦርድ",
  workspace: "የሥራ ቦታ",
  inbox: "መልዕክት ሳጥን",

  name: "ስም",
  post: "ለጥፍ",
  team: "ቡድናችን",

  aboutJob: "ስለ ሥራው",
  signOut: "ውጣ",
  jobDetails: "የሥራ ዝርዝሮች",
  title: "ርዕስ",
  language: "ቋንቋ",
};
const teamsAm = [
  {
    name: "Oliver Benjamin",
    img: "/photo-1560250097-0b93528c311a.avif",
    description:
      "የቅጥር መድረኮችን በሰው ሰራሽ ብልህነት ለማስፋፋት የስትራቴጂ እና የራዕይ መመሪያ",
    stars: 4.5,
    halfStar: true,
    color: "bg-sky-600",
    title: "ዋና ሥራ አስፈጻሚ",
  },
  {
    name: "Emily Grace",
    img: "/photo-1494790108377-be9c29b29330.avif",
    description:
      "አስተዳደር ቡድኖችን እና የስራ አፈጻጸምን በመቆጣጠር የተረጋጋ እና ታማኝ ኦፕሬሽኖችን ማረጋገጥ",
    stars: 5,
    halfStar: false,
    color: "bg-pink-500",
    title: "የቡድን መሪ",
  },
  {
    name: "Alexander Carter",
    img: "/photo-1599566150163-29194dcaad36.avif",
    description:
      "የፋይናንስ እቅድ፣ ተገዢነት እና የረጅም ጊዜ እድገትን መቆጣጠር",
    stars: 5,
    halfStar: false,
    color: "bg-green-500",
    title: "ዋና የፋይናንስ ኦፊሰር",
  },
  {
    name: "Thomas Anderson",
    img: "/premium_photo-1689539137236-b68e436248de.avif",
    description:
      "ዕለታዊ ተግባራትን መደገፍ፣ ማቀናበር እና የመሠረታዊ ሂደቶችን ስርዓት ማረጋገጥ",
    stars: 3,
    halfStar: true,
    color: "bg-yellow-500",
    title: "ረዳት",
  },
];
const categoriesAm = [
  { id: 1, name: "ጤና እና ሕክምና" },
  { id: 2, name: "ቴክኖሎጂ መረጃ (IT) እና ሶፍትዌር" },
  { id: 3, name: "ትምህርት እና ማስተማር" },
  { id: 4, name: "ምህንድስና እና ቴክኒክ" },
  { id: 5, name: "ፋይናንስ እና አካውንቲንግ" },
  { id: 6, name: "ሽያጭ እና ማርኬቲንግ" },
  { id: 7, name: "ሰብዓዊ ኃይል እና አስተዳደር" },
  { id: 8, name: "ፈጠራ እና ንድፍ ንድፍ" },
  { id: 9, name: "እንግዳነት እና ቱሪዝም" },
  { id: 10, name: "ማንፋክቸሪንግ እና ንግድ ስራዎች" },
];
const jobTypesAm = [
  { id: 1, name: "ሙሉ ሰዓት" },
  { id: 2, name: "ከፍተኛ ሰዓት" },
  { id: 3, name: "ውል" },
  { id: 4, name: "ጊዜያዊ" },
  { id: 5, name: "ተማሪ ሥራ" },
  { id: 6, name: "ነጻ ሥራ / ፍሪላንስ" },
  { id: 7, name: "ከሩቅ የሥራ ቦታ" },
  { id: 8, name: "ሚሽስ / አንደኛ እና ከሩቅ" },
  { id: 9, name: "በስፍራ ላይ" },
  { id: 10, name: "ወቅታዊ" },
  { id: 11, name: "ተከታታይ ሥራ" },
  { id: 12, name: "ማማር ሥራ" },
];
const countriesAm: countriesType[] = [
  { id: 1, name: "አፍጋኒስታን", flag: "https://flagcdn.com/w40/af.png" },
  { id: 2, name: "አላንድ ደሴቶች", flag: "https://flagcdn.com/w40/ax.png" },
  { id: 3, name: "አልባኒያ", flag: "https://flagcdn.com/w40/al.png" },
  { id: 4, name: "አልጄሪያ", flag: "https://flagcdn.com/w40/dz.png" },
  { id: 5, name: "አሜሪካ ሳሞአ", flag: "https://flagcdn.com/w40/as.png" },
  { id: 6, name: "አንዶራ", flag: "https://flagcdn.com/w40/ad.png" },
  { id: 7, name: "አንጎላ", flag: "https://flagcdn.com/w40/ao.png" },
  { id: 8, name: "አንጉኢላ", flag: "https://flagcdn.com/w40/ai.png" },
  { id: 9, name: "አንታርክቲካ", flag: "https://flagcdn.com/w40/aq.png" },
  { id: 10, name: "አንቲጉአ እና ባርቡዳ", flag: "https://flagcdn.com/w40/ag.png" },

  { id: 11, name: "አርጀንቲና", flag: "https://flagcdn.com/w40/ar.png" },
  { id: 12, name: "አርሜኒያ", flag: "https://flagcdn.com/w40/am.png" },
  { id: 13, name: "አሩባ", flag: "https://flagcdn.com/w40/aw.png" },
  { id: 14, name: "አውስትራሊያ", flag: "https://flagcdn.com/w40/au.png" },
  { id: 15, name: "ኦስትሪያ", flag: "https://flagcdn.com/w40/at.png" },
  { id: 16, name: "አዘርባጃን", flag: "https://flagcdn.com/w40/az.png" },
  { id: 17, name: "ባሃማስ", flag: "https://flagcdn.com/w40/bs.png" },
  { id: 18, name: "ባህሬን", flag: "https://flagcdn.com/w40/bh.png" },
  { id: 19, name: "ባንግላዲሽ", flag: "https://flagcdn.com/w40/bd.png" },
  { id: 20, name: "ባርቤዶስ", flag: "https://flagcdn.com/w40/bb.png" },

  { id: 21, name: "ቤላሩስ", flag: "https://flagcdn.com/w40/by.png" },
  { id: 22, name: "ቤልጄም", flag: "https://flagcdn.com/w40/be.png" },
  { id: 23, name: "ቤሊዘ", flag: "https://flagcdn.com/w40/bz.png" },
  { id: 24, name: "ቤኒን", flag: "https://flagcdn.com/w40/bj.png" },
  { id: 25, name: "ቤርሙዳ", flag: "https://flagcdn.com/w40/bm.png" },
  { id: 26, name: "ቡታን", flag: "https://flagcdn.com/w40/bt.png" },
  { id: 27, name: "ቦሊቪያ", flag: "https://flagcdn.com/w40/bo.png" },
  { id: 28, name: "ቦኔር፣ ሲንት ኢውስታሲየስ እና ሳባ", flag: "https://flagcdn.com/w40/bq.png" },
  { id: 29, name: "ቦስኒያ እና ሄርዞግቪና", flag: "https://flagcdn.com/w40/ba.png" },
  { id: 30, name: "ቦትስዋና", flag: "https://flagcdn.com/w40/bw.png" },

  { id: 31, name: "ቡቬ ደሴት", flag: "https://flagcdn.com/w40/bv.png" },
  { id: 32, name: "ብራዚል", flag: "https://flagcdn.com/w40/br.png" },
  { id: 33, name: "ብሪትሽ ሕንድ የባህር አካባቢ", flag: "https://flagcdn.com/w40/io.png" },
  { id: 34, name: "ብሩኔይ", flag: "https://flagcdn.com/w40/bn.png" },
  { id: 35, name: "ቡልጌሪያ", flag: "https://flagcdn.com/w40/bg.png" },
  { id: 36, name: "ቡርኪና ፋሶ", flag: "https://flagcdn.com/w40/bf.png" },
  { id: 37, name: "ቡሩንዲ", flag: "https://flagcdn.com/w40/bi.png" },
  { id: 38, name: "ካቦ ቬርዴ", flag: "https://flagcdn.com/w40/cv.png" },
  { id: 39, name: "ካምቦዲያ", flag: "https://flagcdn.com/w40/kh.png" },
  { id: 40, name: "ካሜሩን", flag: "https://flagcdn.com/w40/cm.png" },

  { id: 41, name: "ካናዳ", flag: "https://flagcdn.com/w40/ca.png" },
  { id: 42, name: "ኬማን ደሴቶች", flag: "https://flagcdn.com/w40/ky.png" },
  { id: 43, name: "የማእከላዊ አፍሪካ ሪፐብሊክ", flag: "https://flagcdn.com/w40/cf.png" },
  { id: 44, name: "ቻድ", flag: "https://flagcdn.com/w40/td.png" },
  { id: 45, name: "ቺሊ", flag: "https://flagcdn.com/w40/cl.png" },
  { id: 46, name: "ቻይና", flag: "https://flagcdn.com/w40/cn.png" },
  { id: 47, name: "ክሪስማስ ደሴት", flag: "https://flagcdn.com/w40/cx.png" },
  { id: 48, name: "ኮኮስ (ኪሊንግ) ደሴቶች", flag: "https://flagcdn.com/w40/cc.png" },
  { id: 49, name: "ኮሎምቢያ", flag: "https://flagcdn.com/w40/co.png" },
  { id: 50, name: "ኮሞሮስ", flag: "https://flagcdn.com/w40/km.png" },

  { id: 51, name: "ኮንጎ (ዲኤርሲ)", flag: "https://flagcdn.com/w40/cd.png" },
  { id: 52, name: "ኮንጎ (ሪፐብሊክ)", flag: "https://flagcdn.com/w40/cg.png" },
  { id: 53, name: "ኩክ ደሴቶች", flag: "https://flagcdn.com/w40/ck.png" },
  { id: 54, name: "ኮስታ ሪካ", flag: "https://flagcdn.com/w40/cr.png" },
  { id: 55, name: "ኮት ዲቭዋር", flag: "https://flagcdn.com/w40/ci.png" },
  { id: 56, name: "ክሮኤሽያ", flag: "https://flagcdn.com/w40/hr.png" },
  { id: 57, name: "ኩባ", flag: "https://flagcdn.com/w40/cu.png" },
  { id: 58, name: "ኩራሳኦ", flag: "https://flagcdn.com/w40/cw.png" },
  { id: 59, name: "ሳይፕረስ", flag: "https://flagcdn.com/w40/cy.png" },
  { id: 60, name: "ቼክ ሪፐብሊክ", flag: "https://flagcdn.com/w40/cz.png" },

  { id: 61, name: "ዴንማርክ", flag: "https://flagcdn.com/w40/dk.png" },
  { id: 62, name: "ጅቡቲ", flag: "https://flagcdn.com/w40/dj.png" },
  { id: 63, name: "ዶሚኒካ", flag: "https://flagcdn.com/w40/dm.png" },
  { id: 64, name: "የዶሚኒካ ሪፐብሊክ", flag: "https://flagcdn.com/w40/do.png" },
  { id: 65, name: "ኢኳዶር", flag: "https://flagcdn.com/w40/ec.png" },
  { id: 66, name: "ግብጽ", flag: "https://flagcdn.com/w40/eg.png" },
  { id: 67, name: "ኤል ሳልቫዶር", flag: "https://flagcdn.com/w40/sv.png" },
  { id: 68, name: "ኢኳቶሪያል ጊኒ", flag: "https://flagcdn.com/w40/gq.png" },
  { id: 69, name: "ኤርትራ", flag: "https://flagcdn.com/w40/er.png" },
  { id: 70, name: "ኤስቶኒያ", flag: "https://flagcdn.com/w40/ee.png" },

  { id: 71, name: "ኤስዋቲኒ", flag: "https://flagcdn.com/w40/sz.png" },
  { id: 72, name: "ኢትዮጵያ", flag: "https://flagcdn.com/w40/et.png" },
  { id: 73, name: "ፎክላንድ ደሴቶች", flag: "https://flagcdn.com/w40/fk.png" },
  { id: 74, name: "ፋሮ ደሴቶች", flag: "https://flagcdn.com/w40/fo.png" },
  { id: 75, name: "ፊጂ", flag: "https://flagcdn.com/w40/fj.png" },
  { id: 76, name: "ፊንላንድ", flag: "https://flagcdn.com/w40/fi.png" },
  { id: 77, name: "ፈረንሳይ", flag: "https://flagcdn.com/w40/fr.png" },
  { id: 78, name: "ፈረንሳይ ጉያና", flag: "https://flagcdn.com/w40/gf.png" },
  { id: 79, name: "ፈረንሳይ ፖሊኔዢያ", flag: "https://flagcdn.com/w40/pf.png" },
  { id: 80, name: "ፈረንሳይ ደቡባዊ አካባቢ", flag: "https://flagcdn.com/w40/tf.png" },

  { id: 81, name: "ጋቦን", flag: "https://flagcdn.com/w40/ga.png" },
  { id: 82, name: "ጋምቢያ", flag: "https://flagcdn.com/w40/gm.png" },
  { id: 83, name: "ጆርጂያ", flag: "https://flagcdn.com/w40/ge.png" },
  { id: 84, name: "ጀርመን", flag: "https://flagcdn.com/w40/de.png" },
  { id: 85, name: "ጋና", flag: "https://flagcdn.com/w40/gh.png" },
  { id: 86, name: "ጂብራልታር", flag: "https://flagcdn.com/w40/gi.png" },
  { id: 87, name: "ግሪክ", flag: "https://flagcdn.com/w40/gr.png" },
  { id: 88, name: "ግሪንላንድ", flag: "https://flagcdn.com/w40/gl.png" },
  { id: 89, name: "ግሬናዳ", flag: "https://flagcdn.com/w40/gd.png" },
  { id: 90, name: "ጓደሉፕ", flag: "https://flagcdn.com/w40/gp.png" },

  { id: 91, name: "ጉአም", flag: "https://flagcdn.com/w40/gu.png" },
  { id: 92, name: "ጉዋቲማላ", flag: "https://flagcdn.com/w40/gt.png" },
  { id: 93, name: "ጉርንሲ", flag: "https://flagcdn.com/w40/gg.png" },
  { id: 94, name: "ጊኒ", flag: "https://flagcdn.com/w40/gn.png" },
  { id: 95, name: "ጊኒ-ቢሳው", flag: "https://flagcdn.com/w40/gw.png" },
  { id: 96, name: "ጉያና", flag: "https://flagcdn.com/w40/gy.png" },
  { id: 97, name: "ሃይቲ", flag: "https://flagcdn.com/w40/ht.png" },
  { id: 98, name: "ሀርድ ደሴት እና ማክዶናልድ ደሴቶች", flag: "https://flagcdn.com/w40/hm.png" },
  { id: 99, name: "ቅዱስ ኪሳነ", flag: "https://flagcdn.com/w40/va.png" },
  { id: 100, name: "ሆንዱራስ", flag: "https://flagcdn.com/w40/hn.png" },
  { id: 101, name: "ሆንግ ኮንግ", flag: "https://flagcdn.com/w40/hk.png" },
  { id: 102, name: "ሀንጋሪ", flag: "https://flagcdn.com/w40/hu.png" },
  { id: 103, name: "አይስላንድ", flag: "https://flagcdn.com/w40/is.png" },
  { id: 104, name: "ህንድ", flag: "https://flagcdn.com/w40/in.png" },
  { id: 105, name: "እንዶኔዢያ", flag: "https://flagcdn.com/w40/id.png" },
  { id: 106, name: "ኢራን", flag: "https://flagcdn.com/w40/ir.png" },
  { id: 107, name: "ኢራቅ", flag: "https://flagcdn.com/w40/iq.png" },
  { id: 108, name: "አየርላንድ", flag: "https://flagcdn.com/w40/ie.png" },
  { id: 109, name: "የማን ደሴት", flag: "https://flagcdn.com/w40/im.png" },
  { id: 110, name: "እስራኤል", flag: "https://flagcdn.com/w40/il.png" },

  { id: 111, name: "ጣሊያን", flag: "https://flagcdn.com/w40/it.png" },
  { id: 112, name: "ጃማይካ", flag: "https://flagcdn.com/w40/jm.png" },
  { id: 113, name: "ጃፓን", flag: "https://flagcdn.com/w40/jp.png" },
  { id: 114, name: "ጀርሲ", flag: "https://flagcdn.com/w40/je.png" },
  { id: 115, name: "ጆርዳን", flag: "https://flagcdn.com/w40/jo.png" },
  { id: 116, name: "ካዛኪስታን", flag: "https://flagcdn.com/w40/kz.png" },
  { id: 117, name: "ኬኒያ", flag: "https://flagcdn.com/w40/ke.png" },
  { id: 118, name: "ኪሪባቲ", flag: "https://flagcdn.com/w40/ki.png" },
  { id: 119, name: "ኩዌት", flag: "https://flagcdn.com/w40/kw.png" },
  { id: 120, name: "ኬርጊዝስታን", flag: "https://flagcdn.com/w40/kg.png" },

  { id: 121, name: "ላኦስ", flag: "https://flagcdn.com/w40/la.png" },
  { id: 122, name: "ላቲቪያ", flag: "https://flagcdn.com/w40/lv.png" },
  { id: 123, name: "ሌባኖን", flag: "https://flagcdn.com/w40/lb.png" },
  { id: 124, name: "ሌሶቶ", flag: "https://flagcdn.com/w40/ls.png" },
  { id: 125, name: "ላይቤሪያ", flag: "https://flagcdn.com/w40/lr.png" },
  { id: 126, name: "ሊቢያ", flag: "https://flagcdn.com/w40/ly.png" },
  { id: 127, name: "ሊችተንስታይን", flag: "https://flagcdn.com/w40/li.png" },
  { id: 128, name: "ሊቱዌኒያ", flag: "https://flagcdn.com/w40/lt.png" },
  { id: 129, name: "ሉክሰምበርግ", flag: "https://flagcdn.com/w40/lu.png" },
  { id: 130, name: "ማካዎ", flag: "https://flagcdn.com/w40/mo.png" },

  { id: 131, name: "ማዳጋስካር", flag: "https://flagcdn.com/w40/mg.png" },
  { id: 132, name: "ማላዊ", flag: "https://flagcdn.com/w40/mw.png" },
  { id: 133, name: "ማሌዢያ", flag: "https://flagcdn.com/w40/my.png" },
  { id: 134, name: "ማልዲቭስ", flag: "https://flagcdn.com/w40/mv.png" },
  { id: 135, name: "ማሊ", flag: "https://flagcdn.com/w40/ml.png" },
  { id: 136, name: "ማልታ", flag: "https://flagcdn.com/w40/mt.png" },
  { id: 137, name: "ማርሻል ደሴቶች", flag: "https://flagcdn.com/w40/mh.png" },
  { id: 138, name: "ማርቲኒክ", flag: "https://flagcdn.com/w40/mq.png" },
  { id: 139, name: "ሞሪታኒያ", flag: "https://flagcdn.com/w40/mr.png" },
  { id: 140, name: "ሞሪሸስ", flag: "https://flagcdn.com/w40/mu.png" },

  { id: 141, name: "ማዮት", flag: "https://flagcdn.com/w40/yt.png" },
  { id: 142, name: "ሜክሲኮ", flag: "https://flagcdn.com/w40/mx.png" },
  { id: 143, name: "ሚክሮኔዢያ", flag: "https://flagcdn.com/w40/fm.png" },
  { id: 144, name: "ሞልዶቫ", flag: "https://flagcdn.com/w40/md.png" },
  { id: 145, name: "ሞናኮ", flag: "https://flagcdn.com/w40/mc.png" },
  { id: 146, name: "ሞንጎሊያ", flag: "https://flagcdn.com/w40/mn.png" },
  { id: 147, name: "ሞንቴኔግሮ", flag: "https://flagcdn.com/w40/me.png" },
  { id: 148, name: "ሞንሰራት", flag: "https://flagcdn.com/w40/ms.png" },
  { id: 149, name: "ሞሮኮ", flag: "https://flagcdn.com/w40/ma.png" },
  { id: 150, name: "ሞዛምቢክ", flag: "https://flagcdn.com/w40/mz.png" },

  { id: 151, name: "ሚያንማር", flag: "https://flagcdn.com/w40/mm.png" },
  { id: 152, name: "ናሚቢያ", flag: "https://flagcdn.com/w40/na.png" },
  { id: 153, name: "ናኡሩ", flag: "https://flagcdn.com/w40/nr.png" },
  { id: 154, name: "ኔፓል", flag: "https://flagcdn.com/w40/np.png" },
  { id: 155, name: "ኔዘርላንድ", flag: "https://flagcdn.com/w40/nl.png" },
  { id: 156, name: "ኒው ካሌዶኒያ", flag: "https://flagcdn.com/w40/nc.png" },
  { id: 157, name: "ኒው ዚላንድ", flag: "https://flagcdn.com/w40/nz.png" },
  { id: 158, name: "ኒካራጓ", flag: "https://flagcdn.com/w40/ni.png" },
  { id: 159, name: "ኒጀር", flag: "https://flagcdn.com/w40/ne.png" },
  { id: 160, name: "ናይጄሪያ", flag: "https://flagcdn.com/w40/ng.png" },

  { id: 161, name: "የሰሜን ማደከርያ ማቅናት", flag: "https://flagcdn.com/w40/mk.png" },
  { id: 162, name: "ኖርዌይ", flag: "https://flagcdn.com/w40/no.png" },
  { id: 163, name: "ኦማን", flag: "https://flagcdn.com/w40/om.png" },
  { id: 164, name: "ፓኪስታን", flag: "https://flagcdn.com/w40/pk.png" },
  { id: 165, name: "ፓላው", flag: "https://flagcdn.com/w40/pw.png" },
  { id: 166, name: "ፍልስጤን", flag: "https://flagcdn.com/w40/ps.png" },
  { id: 167, name: "ፓናማ", flag: "https://flagcdn.com/w40/pa.png" },
  { id: 168, name: "ፓፑዋ ኒው ጊኒ", flag: "https://flagcdn.com/w40/pg.png" },
  { id: 169, name: "ፓራጓይ", flag: "https://flagcdn.com/w40/py.png" },
  { id: 170, name: "ፐሩ", flag: "https://flagcdn.com/w40/pe.png" },

  { id: 171, name: "ፊሊፒንስ", flag: "https://flagcdn.com/w40/ph.png" },
  { id: 172, name: "ፒትካይርን ደሴቶች", flag: "https://flagcdn.com/w40/pn.png" },
  { id: 173, name: "ፖላንድ", flag: "https://flagcdn.com/w40/pl.png" },
  { id: 174, name: "ፖርቱጋል", flag: "https://flagcdn.com/w40/pt.png" },
  { id: 175, name: "ፖርታ ሪኮ", flag: "https://flagcdn.com/w40/pr.png" },
  { id: 176, name: "ቃታር", flag: "https://flagcdn.com/w40/qa.png" },
  { id: 177, name: "ሪኡኒየን", flag: "https://flagcdn.com/w40/re.png" },
  { id: 178, name: "ሮማኒያ", flag: "https://flagcdn.com/w40/ro.png" },
  { id: 179, name: "ሩሲያ", flag: "https://flagcdn.com/w40/ru.png" },
  { id: 180, name: "ሩዋንዳ", flag: "https://flagcdn.com/w40/rw.png" },

  { id: 181, name: "ሴንት ባርቴሌሚ", flag: "https://flagcdn.com/w40/bl.png" },
  { id: 182, name: "ሴንት ሄለና፣ አስንሽን እና ትሪስታን ዳ ኩንሃ", flag: "https://flagcdn.com/w40/sh.png" },
  { id: 183, name: "ሴንት ኪትስ እና ኔቪስ", flag: "https://flagcdn.com/w40/kn.png" },
  { id: 184, name: "ሴንት ሉሲያ", flag: "https://flagcdn.com/w40/lc.png" },
  { id: 185, name: "ሴንት ማርቲን", flag: "https://flagcdn.com/w40/mf.png" },
  { id: 186, name: "ሴንት ፒየር እና ሚኩሎን", flag: "https://flagcdn.com/w40/pm.png" },
  { id: 187, name: "ሴንት ቪንሴንት እና ግሬናዲንስ", flag: "https://flagcdn.com/w40/vc.png" },
  { id: 188, name: "ሳሞአ", flag: "https://flagcdn.com/w40/ws.png" },
  { id: 189, name: "ሳን ማሪኖ", flag: "https://flagcdn.com/w40/sm.png" },
  { id: 190, name: "ሳኦ ቶሜ እና ፕሪንሲፔ", flag: "https://flagcdn.com/w40/st.png" },

  { id: 191, name: "ሳውዲ አረቢያ", flag: "https://flagcdn.com/w40/sa.png" },
  { id: 192, name: "ሴኔጋል", flag: "https://flagcdn.com/w40/sn.png" },
  { id: 193, name: "ሰርቢያ", flag: "https://flagcdn.com/w40/rs.png" },
  { id: 194, name: "ሴሸል", flag: "https://flagcdn.com/w40/sc.png" },
  { id: 195, name: "ሴራ ሊዎን", flag: "https://flagcdn.com/w40/sl.png" },
  { id: 196, name: "ሲንጋፖር", flag: "https://flagcdn.com/w40/sg.png" },
  { id: 197, name: "ሲንት ማርተን", flag: "https://flagcdn.com/w40/sx.png" },
  { id: 198, name: "ስሎቫኪያ", flag: "https://flagcdn.com/w40/sk.png" },
  { id: 199, name: "ስሎቬኒያ", flag: "https://flagcdn.com/w40/si.png" },
  { id: 200, name: "ሰሎሞን ደሴቶች", flag: "https://flagcdn.com/w40/sb.png" },
  { id: 201, name: "ሶማሊያ", flag: "https://flagcdn.com/w40/so.png" },
  { id: 202, name: "ደቡብ አፍሪካ", flag: "https://flagcdn.com/w40/za.png" },
  { id: 203, name: "ደቡብ ጆርጂያ እና ደቡብ ሳንድዊች ደሴቶች", flag: "https://flagcdn.com/w40/gs.png" },
  { id: 204, name: "ደቡብ ኮሪያ", flag: "https://flagcdn.com/w40/kr.png" },
  { id: 205, name: "ደቡብ ሱዳን", flag: "https://flagcdn.com/w40/ss.png" },
  { id: 206, name: "ስፔን", flag: "https://flagcdn.com/w40/es.png" },
  { id: 207, name: "ስሪ ላንካ", flag: "https://flagcdn.com/w40/lk.png" },
  { id: 208, name: "ሱዳን", flag: "https://flagcdn.com/w40/sd.png" },
  { id: 209, name: "ሱሪናም", flag: "https://flagcdn.com/w40/sr.png" },
  { id: 210, name: "ስቫልባርድ እና ጃን ማየን", flag: "https://flagcdn.com/w40/sj.png" },

  { id: 211, name: "ስዊድን", flag: "https://flagcdn.com/w40/se.png" },
  { id: 212, name: "ስዊዘርላንድ", flag: "https://flagcdn.com/w40/ch.png" },
  { id: 213, name: "ሲሪያ", flag: "https://flagcdn.com/w40/sy.png" },
  { id: 214, name: "ታይዋን", flag: "https://flagcdn.com/w40/tw.png" },
  { id: 215, name: "ታጂኪስታን", flag: "https://flagcdn.com/w40/tj.png" },
  { id: 216, name: "ታንዛኒያ", flag: "https://flagcdn.com/w40/tz.png" },
  { id: 217, name: "ታይላንድ", flag: "https://flagcdn.com/w40/th.png" },
  { id: 218, name: "ቲሞር-ሌስቴ", flag: "https://flagcdn.com/w40/tl.png" },
  { id: 219, name: "ቶጎ", flag: "https://flagcdn.com/w40/tg.png" },
  { id: 220, name: "ቶኬላው", flag: "https://flagcdn.com/w40/tk.png" },

  { id: 221, name: "ቶንጋ", flag: "https://flagcdn.com/w40/to.png" },
  { id: 222, name: "ትሪኒዳድ እና ቶባጎ", flag: "https://flagcdn.com/w40/tt.png" },
  { id: 223, name: "ቱኒዚያ", flag: "https://flagcdn.com/w40/tn.png" },
  { id: 224, name: "ቱርክ", flag: "https://flagcdn.com/w40/tr.png" },
  { id: 225, name: "ቱርክመኒስታን", flag: "https://flagcdn.com/w40/tm.png" },
  { id: 226, name: "ቱቫሉ", flag: "https://flagcdn.com/w40/tv.png" },
  { id: 227, name: "ዩጋንዳ", flag: "https://flagcdn.com/w40/ug.png" },
  { id: 228, name: "ዩክሬን", flag: "https://flagcdn.com/w40/ua.png" },
  { id: 229, name: "የአረብ ኤምሬትስ ህብረት", flag: "https://flagcdn.com/w40/ae.png" },
  { id: 230, name: "ዩናይትድ ኪንግደም", flag: "https://flagcdn.com/w40/gb.png" },

  { id: 231, name: "ዩናይትድ ስቴትስ", flag: "https://flagcdn.com/w40/us.png" },
  { id: 232, name: "ኡራጉዋይ", flag: "https://flagcdn.com/w40/uy.png" },
  { id: 233, name: "ኡዝበኪስታን", flag: "https://flagcdn.com/w40/uz.png" },
  { id: 234, name: "ቫኑአቱ", flag: "https://flagcdn.com/w40/vu.png" },
  { id: 235, name: "ቬኔዙዌላ", flag: "https://flagcdn.com/w40/ve.png" },
  { id: 236, name: "ቬትናም", flag: "https://flagcdn.com/w40/vn.png" },
  { id: 237, name: "የብሪትሽ ቫርጂን ደሴቶች", flag: "https://flagcdn.com/w40/vg.png" },
  { id: 238, name: "የአሜሪካ ቫርጂን ደሴቶች", flag: "https://flagcdn.com/w40/vi.png" },
  { id: 239, name: "ዋሊስ እና ፉቱና", flag: "https://flagcdn.com/w40/wf.png" },
  { id: 240, name: "ምዕራባዊ ሳህራ", flag: "https://flagcdn.com/w40/eh.png" },

  { id: 241, name: "የይመን", flag: "https://flagcdn.com/w40/ye.png" },
  { id: 242, name: "ዛምቢያ", flag: "https://flagcdn.com/w40/zm.png" },
  { id: 243, name: "ዝምቢቤ", flag: "https://flagcdn.com/w40/zw.png" },
  { id: 244, name: "ኮሶቮ", flag: "https://flagcdn.com/w40/xk.png" },
  { id: 245, name: "ሶማላንድ", flag: "https://flagcdn.com/w40/so.png" }, // unofficial
  { id: 246, name: "ታይዋን (የቻይና ሪፐብሊክ)", flag: "https://flagcdn.com/w40/tw.png" }, // duplicate
  { id: 247, name: "ፍልስጤን", flag: "https://flagcdn.com/w40/ps.png" }, // duplicate
  { id: 248, name: "ደቡብ ኦሴቲያ", flag: "https://flagcdn.com/w40/rs.png" }, // unofficial
  { id: 249, name: "አብኪያ", flag: "https://flagcdn.com/w40/ge.png" }, // unofficial
];
export default amharic;
export { arabic };
export { french };
export { english };
export {teamsAm};
export {teamsEn};
export {teamsFr};
export {teamsAr};
export {categoriesAm};
export {categoriesAr};
export {categoriesEn};
export {categoriesFr};
export {jobTypesAm};
export {jobTypesAr};
export {jobTypesEn};
export {jobTypesFr};
export {countriesAm};
export {countriesAr};
export {countriesEn};
export {countriesFr};
 